<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Activate your account</name>
   <tag></tag>
   <elementGuidId>0cee4d94-e599-4e87-8965-49751a4b2690</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id=':2c']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>809189bf-6659-4dae-aa8e-d4a3dfd8c9d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-thread-id</name>
      <type>Main</type>
      <value>#thread-f:1749485740498421787</value>
      <webElementGuid>e752d7c6-73b4-4f13-b8bd-9adafb009a6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-legacy-thread-id</name>
      <type>Main</type>
      <value>18476c030605081b</value>
      <webElementGuid>3fd6c78f-95e1-4369-a136-728fe73bd86c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-legacy-last-message-id</name>
      <type>Main</type>
      <value>18476c041a9f2c17</value>
      <webElementGuid>948f5d8e-8717-4087-810c-5d0d2f4cfe13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-legacy-last-non-draft-message-id</name>
      <type>Main</type>
      <value>18476c041a9f2c17</value>
      <webElementGuid>e1e68e0c-1d4d-4e53-b5a7-f3dcfd48f0d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Activate your account.</value>
      <webElementGuid>606639af-fdc6-4677-984a-6b05e9318dd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:2c&quot;)/span[1]</value>
      <webElementGuid>2ada973a-a2cb-4442-8d69-23e68de8da9f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id=':2c']/span</value>
      <webElementGuid>272ae3b3-91f2-4aa6-bb7e-776f3e846e3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='info'])[2]/following::span[3]</value>
      <webElementGuid>da04fd25-02ba-4312-a3fd-bd8b1737e2ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Activate your account.'])[1]/following::span[6]</value>
      <webElementGuid>e4bf0f8e-4abc-4c9e-b5e7-1cd260ae880d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Google Community Te.'])[1]/preceding::span[6]</value>
      <webElementGuid>1e8291cf-ac29-4669-a0b5-22df6f24d6cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/div/div/div/span/span</value>
      <webElementGuid>cf2c5d02-b479-4500-963e-c00f4c29ce32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Activate your account.' or . = 'Activate your account.')]</value>
      <webElementGuid>698b7bc4-d59d-4083-9165-8358808377d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
