<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Activate your account</name>
   <tag></tag>
   <elementGuidId>759381bc-9af2-400c-b993-d5ed504e9f65</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h2[@id=':5f']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>d9809276-ba0b-4c58-ac05-6efc7f6c6649</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>:5f</value>
      <webElementGuid>ff575780-1a85-4971-98e2-1510f5ab78b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hP</value>
      <webElementGuid>02919085-d31b-4d8e-a9f0-3b5f89207797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>ee2211ed-64ce-4178-84cd-9e180c028466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-thread-perm-id</name>
      <type>Main</type>
      <value>thread-f:1749485740498421787</value>
      <webElementGuid>ae665617-e401-4246-b43b-16343ab96b2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-legacy-thread-id</name>
      <type>Main</type>
      <value>18476c030605081b</value>
      <webElementGuid>49155cff-4188-489c-9fea-6289d75a6c2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Activate your account.</value>
      <webElementGuid>a474d25e-5db2-46b7-ac96-38a0432b6e3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:5f&quot;)</value>
      <webElementGuid>eee4bb49-a46a-4802-9fdd-aaee7f5112a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h2[@id=':5f']</value>
      <webElementGuid>5eaf36c8-af15-4023-ad3b-d382f2a4c437</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id=':1']/div/div[2]/div/table/tr/td/div[2]/div/div[2]/div/h2</value>
      <webElementGuid>20acf34e-259c-46a4-bc7f-6cd532f1efc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='inbox settings'])[3]/following::h2[1]</value>
      <webElementGuid>7b8bc3a2-0e26-43f0-a3a1-5748c0cca64e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your Social tab is empty.'])[1]/following::h2[1]</value>
      <webElementGuid>771e2231-a209-4aa6-81d4-cb9ba175819f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inbox'])[2]/preceding::h2[1]</value>
      <webElementGuid>6837b8ca-5c34-4463-a24e-c7856862c8c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='info@carpl.ai'])[1]/preceding::h2[1]</value>
      <webElementGuid>6ede8d0f-a668-4aeb-919e-281b32f19780</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/h2</value>
      <webElementGuid>ec16ac3d-ad24-4f0e-8385-f6e094473233</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[@id = ':5f' and (text() = 'Activate your account.' or . = 'Activate your account.')]</value>
      <webElementGuid>88a48c77-9030-4574-9bb0-42a62e65d820</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
