<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_me_ajT</name>
   <tag></tag>
   <elementGuidId>03e13f3a-6f52-4805-919e-d8bf9cccaf8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id=':6i']/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.ajT</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>dfaa823b-7fc2-4242-9a6f-ec3f2dbe258b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ajT</value>
      <webElementGuid>77e3f0e0-3dac-4942-8155-ecd36a642c8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//ssl.gstatic.com/ui/v1/icons/mail/images/cleardot.gif</value>
      <webElementGuid>5fe006b2-b0ed-4c6a-926a-3136616f7f9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:6i&quot;)/img[@class=&quot;ajT&quot;]</value>
      <webElementGuid>af5b13ac-3fae-4721-a4f5-363309a846a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>dbf1d8b1-59cd-4221-af1b-7732c78005e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ajT</value>
      <webElementGuid>a7f7e0eb-32ed-48b5-a919-28a157410c05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//ssl.gstatic.com/ui/v1/icons/mail/images/cleardot.gif</value>
      <webElementGuid>e32893b7-0789-46ce-8ce8-417832c49061</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:6i&quot;)/img[@class=&quot;ajT&quot;]</value>
      <webElementGuid>cd25e0b8-acdd-43d7-aa42-3e607c656e5f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id=':6i']/img</value>
      <webElementGuid>d21369d0-9004-4107-aea1-08f62f145743</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/img</value>
      <webElementGuid>02363273-cd34-4a3f-a81d-5049ee82de95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '//ssl.gstatic.com/ui/v1/icons/mail/images/cleardot.gif']</value>
      <webElementGuid>b1d16015-3ec2-4482-9b5e-204ef1a6bb9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
