<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Annotation Template</name>
   <tag></tag>
   <elementGuidId>ac909cc1-2db6-4f66-8ba1-dd8c953e8a87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='analysisUl']/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#analysisUl > li > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a09c81ba-4dcb-49e3-8788-5bed0ca8d2cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/annotation_template</value>
      <webElementGuid>35d9ed26-bc5e-4997-a4b8-60178439ec5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Annotation Template</value>
      <webElementGuid>557d8bc4-400c-4c6a-95ba-a952c1339653</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;analysisUl&quot;)/li[1]/a[1]</value>
      <webElementGuid>5f6e1349-7622-4ee3-ac3b-464ba86b757c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>19f00c32-5e6e-4526-b947-6b1467118bd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/annotation_template</value>
      <webElementGuid>ad625785-22ff-440f-893a-eaaef0aaa5c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Annotation Template</value>
      <webElementGuid>d2c01f07-3edc-4553-88b1-cab3dc0f3fbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;analysisUl&quot;)/li[1]/a[1]</value>
      <webElementGuid>e78dd811-2123-4b69-bb2d-2f42e71de65e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>48977baf-3524-4148-90fc-5bd819d00ef4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/annotation_template</value>
      <webElementGuid>3f542f6f-31e2-43e9-b951-d3b2b53f0f1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Annotation Template</value>
      <webElementGuid>80cdc0b9-dd12-4f4e-bdfe-eb97a7a7a7f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;analysisUl&quot;)/li[1]/a[1]</value>
      <webElementGuid>4f3f644e-ab84-4a9b-a0ef-dc0b52082ad1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d5edd0f1-ccec-4bbf-aeb5-698899d2710d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/annotation_template</value>
      <webElementGuid>6e7fa603-786b-4f60-8758-bdaf1421b725</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Annotation Template</value>
      <webElementGuid>20255502-f6fe-42de-87da-11a97e08e8f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;analysisUl&quot;)/li[1]/a[1]</value>
      <webElementGuid>2283632e-6014-4f18-a4c2-2a3e7b8d06d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>36116175-ca54-4be3-89dd-d19992e734eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/annotation_template</value>
      <webElementGuid>ab8cd9ca-ca21-4832-8a42-677b8ed6555b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Annotation Template</value>
      <webElementGuid>ea2fff04-6800-4a29-bbc3-6b34c96cab08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;analysisUl&quot;)/li[1]/a[1]</value>
      <webElementGuid>7b9ed88f-2f9b-4318-8a48-70596401aa5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>005850c9-d14a-4792-ac04-d55e61b73616</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/annotation_template</value>
      <webElementGuid>911b5a8f-9b73-4b1d-a165-da1b290886ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Annotation Template</value>
      <webElementGuid>e860c477-6b1b-4687-8e94-eabceb198d8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;analysisUl&quot;)/li[1]/a[1]</value>
      <webElementGuid>1df1d3aa-2ffa-4ff3-b875-f197e2d0121b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5c34c5a9-d29a-4c14-9c72-514cd444d4fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/annotation_template</value>
      <webElementGuid>663c7f81-5835-4d81-8796-0490b3843f35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Annotation Template</value>
      <webElementGuid>277396b9-d62e-4a5b-b61d-a3aa4a2ac25d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;analysisUl&quot;)/li[1]/a[1]</value>
      <webElementGuid>a73970d8-019f-4da7-9f33-676de06069eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5ae3527d-6e6a-4a10-bf3e-a9122a0639f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/annotation_template</value>
      <webElementGuid>153a7e95-59aa-420c-a65a-64bbce97dd63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Annotation Template</value>
      <webElementGuid>5fe6e914-1e23-4e8d-a897-04fb7c555086</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;analysisUl&quot;)/li[1]/a[1]</value>
      <webElementGuid>52888791-16b5-4a58-b990-ef958cac2452</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>32b3524d-f1be-43d8-a0e6-803d8d7fcbff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/annotation_template</value>
      <webElementGuid>f7d47812-de6a-4801-b8b6-884378f732d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Annotation Template</value>
      <webElementGuid>5d96622f-24e8-41e6-a405-44674b707a24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;analysisUl&quot;)/li[1]/a[1]</value>
      <webElementGuid>cb5e9d96-f68f-4ce9-838f-d907df7671c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f6bc7344-18e7-4adc-8592-25414de40d8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/annotation_template</value>
      <webElementGuid>517f390e-cb4b-4f05-a1dc-8b60ac32703d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Annotation Template</value>
      <webElementGuid>806eeac0-18cf-42af-8df2-27a26eda93dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;analysisUl&quot;)/li[1]/a[1]</value>
      <webElementGuid>1be7abf4-bc2b-4c9c-8907-8df0b720bb58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ed3950cc-7778-46da-a312-684e2c7e059d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/annotation_template</value>
      <webElementGuid>62aac978-2fc7-4408-93b8-d20b2c0dbece</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Annotation Template</value>
      <webElementGuid>43a41559-16c9-4c22-8223-bcf800201d0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;analysisUl&quot;)/li[1]/a[1]</value>
      <webElementGuid>5039b170-5c10-4a86-a855-33831dc0a253</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b69ef43c-c988-480e-b374-31455389a026</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/annotation_template</value>
      <webElementGuid>47a7cfa2-8803-440b-af3c-bbb2aef23bf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Annotation Template</value>
      <webElementGuid>1e70af03-55a7-4446-86a4-108d5e28e404</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;analysisUl&quot;)/li[1]/a[1]</value>
      <webElementGuid>e644fe53-8636-48d5-9d92-01c52f7a89de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d6a967f9-f85b-4762-b950-d2ac4d432553</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/annotation_template</value>
      <webElementGuid>6e832270-ffa4-4643-99c1-1e3e2d3a9005</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Annotation Template</value>
      <webElementGuid>7b1049fc-03db-405c-b7b1-b88674848c33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;analysisUl&quot;)/li[1]/a[1]</value>
      <webElementGuid>8d2b2857-2982-4e4f-82bd-0f0c91ce3492</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f7d26db0-0ddb-4dab-b0ac-85215a0c510b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/annotation_template</value>
      <webElementGuid>642fe606-89fd-4ef4-9a92-14713befce5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Annotation Template</value>
      <webElementGuid>f27fa84a-c00f-4772-8ac6-41375f2a57b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;analysisUl&quot;)/li[1]/a[1]</value>
      <webElementGuid>9bc0802d-3093-432c-9ebc-0c6ff3b67764</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1fde172a-107d-4f29-b0f6-4e8a8681f541</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/annotation_template</value>
      <webElementGuid>c2057113-2980-47a7-acc0-037f5e1913a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Annotation Template</value>
      <webElementGuid>ae4f147b-8830-42ac-90a9-8ae0844d969d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;analysisUl&quot;)/li[1]/a[1]</value>
      <webElementGuid>b5a169e2-6281-49e3-a806-7773351a32f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>95453642-0f7c-4d1b-a71c-94d0553df46f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/annotation_template</value>
      <webElementGuid>02bb8bb5-4f0e-45a3-b507-5c25d408817a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Annotation Template</value>
      <webElementGuid>803dabd8-eab7-4096-81cd-678ba7381f9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;analysisUl&quot;)/li[1]/a[1]</value>
      <webElementGuid>a66f6700-8c25-4ce2-a594-9b066a91c5e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a81186e7-2337-481b-ae75-b32d760ecd5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/annotation_template</value>
      <webElementGuid>703902a8-8704-4035-9315-7b6d13afaec8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Annotation Template</value>
      <webElementGuid>125d82e2-bd57-453e-b415-82f0b63eb219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;analysisUl&quot;)/li[1]/a[1]</value>
      <webElementGuid>e0e3b363-10cb-4abb-b33b-3312f68006df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fe40c968-31c5-44f5-bcab-df4048879933</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/annotation_template</value>
      <webElementGuid>39d298bf-5707-4cf6-aac0-ebb144ee278a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Annotation Template</value>
      <webElementGuid>70efef38-7263-47d7-abdd-050866dd24aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;analysisUl&quot;)/li[1]/a[1]</value>
      <webElementGuid>709cf72f-0f97-4cc8-b7ed-d39097a3d85a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='analysisUl']/li/a</value>
      <webElementGuid>0d0985ed-364d-4ee1-9e39-3a53d2186ef2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Annotation Template')]</value>
      <webElementGuid>abd4da2f-2cfe-444a-8c3c-f35d2042f923</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Annotation'])[1]/following::a[1]</value>
      <webElementGuid>31ceef13-c9a7-4884-a23b-247da27a4907</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dataset Manager'])[1]/following::a[2]</value>
      <webElementGuid>2be13ade-ebe2-4b87-9c67-c247b110a372</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Annotation Project'])[1]/preceding::a[1]</value>
      <webElementGuid>b3593709-09fd-4036-9111-bba22dfc2d27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Track Annotation'])[1]/preceding::a[2]</value>
      <webElementGuid>a681822f-f594-4ca0-a8b8-33bafaa6730c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Annotation Template']/parent::*</value>
      <webElementGuid>0f19dbe7-9115-42ac-a0d8-fa1314273bfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/annotation_template')]</value>
      <webElementGuid>f46b5b0f-9a25-40ce-b301-c13edbb9dadc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/ul/li/a</value>
      <webElementGuid>53b60be7-1f10-4284-9361-7712a0c8831a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/annotation_template' and (text() = 'Annotation Template' or . = 'Annotation Template')]</value>
      <webElementGuid>ac831c4b-1133-4352-b64c-bf2e026abd34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Pull Tracker'])[1]/following::a[2]</value>
      <webElementGuid>72fb0b8a-b9e1-45ca-b5f2-33f529cd2c9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
