<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Draft</name>
   <tag></tag>
   <elementGuidId>5c672cd6-215d-4928-bb56-d633f8648e80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='draft']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;draft&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6a54957a-08dc-407c-bbeb-ffd9731b4a1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>3a753a8f-acfe-4765-8892-05b2bddb0494</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn_new_secondary</value>
      <webElementGuid>328fbef1-73fe-40a7-b740-6d71604efa15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>draft</value>
      <webElementGuid>d90d7967-130e-4e83-852e-90b1593058c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Draft</value>
      <webElementGuid>ab57eac0-4dd1-4af6-ba22-6b6e9d7ff593</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;workflowBottomForm&quot;)/div[@class=&quot;row align-items-center innerData&quot;]/div[@class=&quot;col-4 text-right&quot;]/button[@class=&quot;btn btn_new_secondary&quot;]</value>
      <webElementGuid>6ebdadac-0fb4-4b08-8c23-839c4efd13b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9cf5c723-0605-4d19-866d-f676ef3600be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>4adfe770-0b01-4375-9f53-4f41dc66a6c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn_new_secondary</value>
      <webElementGuid>06539e04-eed3-45f1-a17a-dfdabeb33a69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>draft</value>
      <webElementGuid>cdd330d5-aff0-48d5-b0ca-a1f38fb6c8ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Draft</value>
      <webElementGuid>c0ac9997-4de1-412f-a823-cb56310a7241</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;workflowBottomForm&quot;)/div[@class=&quot;row align-items-center innerData&quot;]/div[@class=&quot;col-4 text-right&quot;]/button[@class=&quot;btn btn_new_secondary&quot;]</value>
      <webElementGuid>f98ea3ce-1391-4792-91fa-381bcfcd4402</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>35d88702-3c6d-4ec2-ae38-41ab8a132b0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>05db1ac0-3612-4a17-8584-30083b924486</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn_new_secondary</value>
      <webElementGuid>af41443c-a3f7-478a-8681-e6cccdd6221b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>draft</value>
      <webElementGuid>88d5a037-f667-44b6-9663-707e3f1bbfc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Draft</value>
      <webElementGuid>87c6ad0f-e3e7-47cf-a16d-915c37e787c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;workflowBottomForm&quot;)/div[@class=&quot;row align-items-center innerData&quot;]/div[@class=&quot;col-4 text-right&quot;]/button[@class=&quot;btn btn_new_secondary&quot;]</value>
      <webElementGuid>14de34aa-17a1-4668-96b5-692b893657ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>31bd451b-a6d5-4d95-b439-41e9355fd074</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>42a373de-8bad-4761-a29a-72b7197ae5b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn_new_secondary</value>
      <webElementGuid>3de96a05-19de-4a86-bb44-fb4091eadaaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>draft</value>
      <webElementGuid>8395a7da-b9d5-4766-85c3-265e8eb2281c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Draft</value>
      <webElementGuid>45325219-8ea7-4bad-afe5-12897b633b71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;workflowBottomForm&quot;)/div[@class=&quot;row align-items-center innerData&quot;]/div[@class=&quot;col-4 text-right&quot;]/button[@class=&quot;btn btn_new_secondary&quot;]</value>
      <webElementGuid>e1e94401-bae7-406a-9447-542ab0203a50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cbe22b75-57e8-4662-8a6c-c8bc8b9a0bf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>3761b4ae-1f22-47b4-8898-4b7c63a61b99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn_new_secondary</value>
      <webElementGuid>d46791ea-5f51-4489-9bbb-c6762fea023b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>draft</value>
      <webElementGuid>df259bb4-4bed-4d6e-b864-c236b1277c98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Draft</value>
      <webElementGuid>9da1c4a1-2ec7-45de-a6f4-76856d972a6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;workflowBottomForm&quot;)/div[@class=&quot;row align-items-center innerData&quot;]/div[@class=&quot;col-4 text-right&quot;]/button[@class=&quot;btn btn_new_secondary&quot;]</value>
      <webElementGuid>c84e7f15-e983-4c4e-ab77-68de8242f4de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>89418a8e-cc96-4ff1-b9a7-42766d5a1dd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>5a5d2010-620a-4824-89ea-edd5c14dd361</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn_new_secondary</value>
      <webElementGuid>5cd1ab51-1905-4ee7-b053-ac2f4ede4b5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>draft</value>
      <webElementGuid>01c053c1-074c-4588-8e12-1ff4d5ce6101</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Draft</value>
      <webElementGuid>3ddd366c-f2e8-4ba8-b9f2-a3f069cf70db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;workflowBottomForm&quot;)/div[@class=&quot;row align-items-center innerData&quot;]/div[@class=&quot;col-4 text-right&quot;]/button[@class=&quot;btn btn_new_secondary&quot;]</value>
      <webElementGuid>aa2da671-dce4-4d91-b1a4-83b49e026acf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>16bb3de1-2092-4961-9ce3-03fd3c9d061c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>a73810a8-9afb-45cf-86c5-b3d1de5cafa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn_new_secondary</value>
      <webElementGuid>50376eb7-2833-4660-9fef-5950046307d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>draft</value>
      <webElementGuid>38e18c2c-7002-45a1-9fb9-f2f269b4f169</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Draft</value>
      <webElementGuid>a41c190d-d714-4c65-87bd-5ff20200e9f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;workflowBottomForm&quot;)/div[@class=&quot;row align-items-center innerData&quot;]/div[@class=&quot;col-4 text-right&quot;]/button[@class=&quot;btn btn_new_secondary&quot;]</value>
      <webElementGuid>fd7737c1-d072-47dc-9b4f-4d6813d75acf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5ac4b9d8-19c7-45dd-8587-b538ccd99efe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>69dccb41-82f2-49a9-af54-e97d090917b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn_new_secondary</value>
      <webElementGuid>38c58857-ce51-41ad-815e-671b822804ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>draft</value>
      <webElementGuid>da248de5-8f71-4908-aa27-5ad4e5a09816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Draft</value>
      <webElementGuid>ec5d2c0d-840f-40d3-93a8-8a972855940e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;workflowBottomForm&quot;)/div[@class=&quot;row align-items-center innerData&quot;]/div[@class=&quot;col-4 text-right&quot;]/button[@class=&quot;btn btn_new_secondary&quot;]</value>
      <webElementGuid>1ecf4138-c778-4986-b2f8-dffa9d26175c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>20681fec-7789-4de8-a410-87663eac61ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>82808ae9-e8a4-4779-bfa1-96b465244378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn_new_secondary</value>
      <webElementGuid>9e0a83b3-47e9-4c25-bd2d-4b7a92925d62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>draft</value>
      <webElementGuid>0bad5085-117b-48d2-80a3-4d759fdb5f2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Draft</value>
      <webElementGuid>7703b31a-2908-4c58-82bb-68582bf7a9f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;workflowBottomForm&quot;)/div[@class=&quot;row align-items-center innerData&quot;]/div[@class=&quot;col-4 text-right&quot;]/button[@class=&quot;btn btn_new_secondary&quot;]</value>
      <webElementGuid>c6de3a9d-18d9-4a1d-9e3c-906f9bdc8db7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cadc7537-5be4-41bb-8e1f-689d755b3842</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>0637cc28-a326-497a-8f99-8fbc2d718b75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn_new_secondary</value>
      <webElementGuid>9ea082b8-b04d-4208-9829-701b5cbd7b75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>draft</value>
      <webElementGuid>409522fc-5fe8-46c6-80aa-408860151c92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Draft</value>
      <webElementGuid>488daae3-9ff5-4fcc-8430-8ef906f088f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;workflowBottomForm&quot;)/div[@class=&quot;row align-items-center innerData&quot;]/div[@class=&quot;col-4 text-right&quot;]/button[@class=&quot;btn btn_new_secondary&quot;]</value>
      <webElementGuid>1cb23626-684d-456f-8152-81408e495f9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>63b97171-56e3-4faf-8c94-2d6145742042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>fed901ee-c752-4bc8-89c9-d5db7eb94e6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn_new_secondary</value>
      <webElementGuid>a1a63fe6-ce2a-43f1-8329-5943239f92b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>draft</value>
      <webElementGuid>33ef1081-8021-4e8f-b5b4-7907357ccc64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Draft</value>
      <webElementGuid>5d16a7a9-50a4-41f2-9ec6-a8053ed97f08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;workflowBottomForm&quot;)/div[@class=&quot;row align-items-center innerData&quot;]/div[@class=&quot;col-4 text-right&quot;]/button[@class=&quot;btn btn_new_secondary&quot;]</value>
      <webElementGuid>a79675c6-f572-48fd-8696-184a15874242</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0c70d210-2787-43ea-97bb-d16986bfd2d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>06346d4a-ce22-483d-8657-8e2e9045ec93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn_new_secondary</value>
      <webElementGuid>5173e864-cecb-473c-b862-38fa5547d954</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>draft</value>
      <webElementGuid>a565f8a8-c37d-4074-9936-ca92b33a7b0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Draft</value>
      <webElementGuid>2d862b7a-e5d2-4117-9d1c-b818457e878e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;workflowBottomForm&quot;)/div[@class=&quot;row align-items-center innerData&quot;]/div[@class=&quot;col-4 text-right&quot;]/button[@class=&quot;btn btn_new_secondary&quot;]</value>
      <webElementGuid>d9edcdf5-9e00-43f3-b5a1-86eaf63b9caf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c436380b-870a-4f54-b2d8-9c85155df718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>8f0d7a8c-3667-440b-86e4-6ea64fbdd8dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn_new_secondary</value>
      <webElementGuid>d401220d-c1a7-4fb5-81ba-92ca61884224</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>draft</value>
      <webElementGuid>352f5bea-9973-444d-a60b-85e4079cc406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Draft</value>
      <webElementGuid>5eb32410-2d46-4a96-94ee-a41ea831ae78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;workflowBottomForm&quot;)/div[@class=&quot;row align-items-center innerData&quot;]/div[@class=&quot;col-4 text-right&quot;]/button[@class=&quot;btn btn_new_secondary&quot;]</value>
      <webElementGuid>ad28f2e5-2912-4e00-b7db-247fe0f31fcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>40d4520b-5f43-49ec-87f4-fcd611d04ebc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>d7d4cb6a-2196-4dba-9f40-6a3195b3f4ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn_new_secondary</value>
      <webElementGuid>b8262a44-4a11-4e7e-a723-efb8bd648b20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>draft</value>
      <webElementGuid>de7303a2-9d6e-4095-83e3-72c450e29d4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Draft</value>
      <webElementGuid>c1e515bd-e2ee-43e5-bbfc-681fc9fda580</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;workflowBottomForm&quot;)/div[@class=&quot;row align-items-center innerData&quot;]/div[@class=&quot;col-4 text-right&quot;]/button[@class=&quot;btn btn_new_secondary&quot;]</value>
      <webElementGuid>cd5c92bb-35db-420e-b86e-2fd93c8ab5fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>08a9643e-e3a1-4086-817b-b2b745fd6907</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>97745e25-5479-4fdc-b83b-5ba72926cbcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn_new_secondary</value>
      <webElementGuid>a14af0ec-4baf-40bb-93b2-3fb58f967b01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>draft</value>
      <webElementGuid>e34a2197-8077-4ebc-bbd7-390c1e8f21a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Draft</value>
      <webElementGuid>3cfc5553-ae37-4986-979d-c124079c3cab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;workflowBottomForm&quot;)/div[@class=&quot;row align-items-center innerData&quot;]/div[@class=&quot;col-4 text-right&quot;]/button[@class=&quot;btn btn_new_secondary&quot;]</value>
      <webElementGuid>73172b5d-318d-4b82-a094-3b546173dafe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='draft']</value>
      <webElementGuid>e1298867-e70f-4dfe-af2b-e75624ad7f0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='workflowBottomForm']/div/div[2]/button[4]</value>
      <webElementGuid>28d6f5a0-d500-4729-95a1-50d5de565068</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CONNECTORS'])[1]/following::button[4]</value>
      <webElementGuid>fe16d2e1-90f8-470e-ac37-04a9c62e533b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Publish'])[1]/preceding::button[1]</value>
      <webElementGuid>ef2d9320-1db5-447d-9f93-c91927ca00c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Draft']/parent::*</value>
      <webElementGuid>f01d21b2-dbd2-4f17-9417-1d0a39814fe4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[4]</value>
      <webElementGuid>969aa0ce-68c4-49d2-adb4-b6b871b82dab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @name = 'draft' and (text() = 'Draft' or . = 'Draft')]</value>
      <webElementGuid>542afb8b-007d-476e-b1ae-0362375c191b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
