<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_fagman  sudocarpl.ai</name>
   <tag></tag>
   <elementGuidId>df2b884e-b02d-4725-867f-f33c11c793a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-2-option-4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#react-select-2-option-4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>39b2a64a-b406-4d9b-ac36-d4c55294885d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> css-1kw004b-option</value>
      <webElementGuid>4ccb3ab5-2caa-4f84-95e8-f12ccead16bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-2-option-4</value>
      <webElementGuid>51fbfc01-3de5-4cc6-9b1e-23da934aada7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>2afcd810-ebe9-4be7-8a09-7d83f1454d49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>fagman : sudo@carpl.ai</value>
      <webElementGuid>a5a16181-e351-4aa0-b0e9-dd3914029527</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-2-option-4&quot;)</value>
      <webElementGuid>a1c3fb56-0d57-43c5-a0ed-7d2c99f85383</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-2-option-4']</value>
      <webElementGuid>68cf005e-82dc-40a7-991c-56db4eb2f5a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Select-Template']/div[2]/div/div[5]</value>
      <webElementGuid>cfd956c2-18c9-4887-99d4-d3b2755bf437</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test user_template_1 : anupam.sachan@carpl.ai'])[1]/following::div[1]</value>
      <webElementGuid>02dfd25e-9c51-4467-94a6-16e9cf9f66b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SAGEMAKER TEMPLATE : sudo@carpl.ai'])[1]/following::div[2]</value>
      <webElementGuid>92041698-0654-4c13-be39-2c45f51b02d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='fabes : sudo@carpl.ai'])[1]/preceding::div[1]</value>
      <webElementGuid>c8f1d223-c8b2-42a0-a7f0-34bff8137cb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test13 : sudo@carpl.ai'])[1]/preceding::div[2]</value>
      <webElementGuid>ba963b95-99c3-4558-b7f5-7dfa07beddf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='fagman : sudo@carpl.ai']/parent::*</value>
      <webElementGuid>9f052744-dcb8-4a4f-8b0b-ddc1f8d53b13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/div/div[5]</value>
      <webElementGuid>521cf510-6e38-4f7f-aac1-bdfd8abea4c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-2-option-4' and (text() = 'fagman : sudo@carpl.ai' or . = 'fagman : sudo@carpl.ai')]</value>
      <webElementGuid>988076b9-cb6f-4589-b7ca-49c69c549747</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
