<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Select</name>
   <tag></tag>
   <elementGuidId>c616eb57-a42c-4222-a95b-71429b769d03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Select-Template']/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>40fe3604-b23d-49ac-b99e-08b6bdc396cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> css-1hwfws3</value>
      <webElementGuid>1ab66707-70c3-48d3-bbd1-b232384e7846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select </value>
      <webElementGuid>63f04e77-defa-42a9-aa7e-a3684eb75a64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Select-Template&quot;)/div[@class=&quot;css-71ak3d-control&quot;]/div[@class=&quot;css-1hwfws3&quot;]</value>
      <webElementGuid>c39a464f-9b7a-4de1-b73e-9433588a63ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>567d3075-c077-443b-ac23-06d82c93aeeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> css-1hwfws3</value>
      <webElementGuid>25ada6b2-898b-40c2-bd4f-6d79adc1399d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select </value>
      <webElementGuid>00e53caf-4df3-491e-9c44-0288bebe5c2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Select-Template&quot;)/div[@class=&quot;css-71ak3d-control&quot;]/div[@class=&quot;css-1hwfws3&quot;]</value>
      <webElementGuid>9ebdefe3-7632-4926-89a2-04b58735af70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c70049ba-5616-4a87-9f4b-e9e212e846c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> css-1hwfws3</value>
      <webElementGuid>1edd3e3e-1bf6-4e18-ad14-4be8faa6416b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select </value>
      <webElementGuid>b99ed285-5e2e-4285-a6a5-9afe127b9d97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Select-Template&quot;)/div[@class=&quot;css-71ak3d-control&quot;]/div[@class=&quot;css-1hwfws3&quot;]</value>
      <webElementGuid>cf240341-b8be-43fd-8bc7-d7ba29189a4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>42fd4998-b0b7-4691-9e66-cdd215f863cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Dropdown-control</value>
      <webElementGuid>7db299f2-e600-47f9-aff0-5a3c0ddbe1f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>e654b27b-db03-4860-bdb1-439164b30712</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select </value>
      <webElementGuid>b7c27304-49ba-428d-aaa7-61ee49517538</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;wrapper appSection&quot;]/div[@class=&quot;content-wrapper&quot;]/div[1]/div[@class=&quot;projectselct&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-4 col-xl-2&quot;]/div[@class=&quot;Dropdown-root half_width is-open&quot;]/div[@class=&quot;Dropdown-control&quot;]</value>
      <webElementGuid>c05f259a-2173-43be-a1f4-d4ac088a5ebf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>56f5a0f8-bf6e-4655-9204-1f0ebeb1575d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Dropdown-control</value>
      <webElementGuid>0ebae659-1c9e-4fe7-aad1-a94dad87998a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>e50401c6-0692-4b31-b8c3-678260798aa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select </value>
      <webElementGuid>ee8e7f26-4941-4ade-8262-e7cd87933675</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;wrapper appSection&quot;]/div[@class=&quot;content-wrapper&quot;]/div[1]/div[@class=&quot;projectselct&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-4 col-xl-2&quot;]/div[@class=&quot;Dropdown-root is-open&quot;]/div[@class=&quot;Dropdown-control&quot;]</value>
      <webElementGuid>92ac762c-86b8-4494-b394-b5f152535258</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fb2da6d1-024b-42a2-9009-438ed7e488f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Dropdown-control</value>
      <webElementGuid>547bf6b8-6aba-4652-8de0-b3c1c97fa263</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>1a0f01d1-c9f0-4d44-b16d-cf4f62579989</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select </value>
      <webElementGuid>2ac66f4e-7c6f-4ffa-8da5-ff0fcdfddac1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;wrapper appSection&quot;]/div[@class=&quot;content-wrapper&quot;]/div[1]/div[@class=&quot;projectselct&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-4 col-xl-2&quot;]/div[@class=&quot;Dropdown-root half_width is-open&quot;]/div[@class=&quot;Dropdown-control&quot;]</value>
      <webElementGuid>b3b0f792-8b63-4624-93b4-0af01841b780</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>066da87a-b018-4d15-a0db-13f1ef4732b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> css-1hwfws3</value>
      <webElementGuid>2d485907-ece4-4942-ae30-55cff1264cab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select </value>
      <webElementGuid>a41050dc-e981-4c4b-a4aa-482bd0260d18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Select-Modality&quot;)/div[@class=&quot;css-71ak3d-control&quot;]/div[@class=&quot;css-1hwfws3&quot;]</value>
      <webElementGuid>87e37d30-9882-4324-96d7-24f0f58cc2d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Select-Template']/div/div</value>
      <webElementGuid>183e8572-b930-41f5-a810-e835cd5fd728</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Annotation Template*'])[1]/following::div[3]</value>
      <webElementGuid>87efe618-be32-4d00-a843-fb0f8ad7861b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Project Description'])[21]/following::div[5]</value>
      <webElementGuid>ddea0b8e-792a-422b-ab2b-ebd1b529248d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='mnist temp : sudo@carpl.ai'])[1]/preceding::div[7]</value>
      <webElementGuid>be59302b-af68-49e6-92f1-03b2689250ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[4]/div/div/div/div</value>
      <webElementGuid>1ca28b32-9947-4110-8955-fbedd81d5b87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Select ' or . = 'Select ')]</value>
      <webElementGuid>6c575010-dcd4-4cbe-83c0-6f6d7e8c0278</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='flipkart : sudo@carpl.ai'])[1]/preceding::div[7]</value>
      <webElementGuid>e6f928d8-ce65-446d-8a3d-45e0594860b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div/div/div</value>
      <webElementGuid>b183a63b-08a2-479d-8489-e152408f1fa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asc'])[1]/following::div[2]</value>
      <webElementGuid>b551e9b7-6c05-4d84-a770-66a99133f192</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select'])[2]/preceding::div[3]</value>
      <webElementGuid>77e767c9-27a9-4c51-bf44-e5925eeef18c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/div/div</value>
      <webElementGuid>e86115cd-c099-4e3d-9280-c2fe1ab1dc49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Select-Modality']/div/div</value>
      <webElementGuid>a87900a4-d8fb-4d1d-aba2-d4bd38844fb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose Modality*'])[1]/following::div[3]</value>
      <webElementGuid>7b65bdfb-9659-4696-ab1f-e052483cc851</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/following::div[5]</value>
      <webElementGuid>4d12df52-da2e-415f-a05d-710bda7939cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CT'])[1]/preceding::div[7]</value>
      <webElementGuid>d96f53fd-8d7e-4ff5-bcea-d6080f3e58a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[4]/div/div/div/div</value>
      <webElementGuid>c3a1d231-784d-4b68-a2d8-473987d35cd5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
