<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Select_css-qqgp34-indicatorContainer</name>
   <tag></tag>
   <elementGuidId>1b77fb32-e7ce-442d-95d1-ed8ccae3a243</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Select-Annotation']/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1b8b288e-7f1f-444f-b2d5-d5b65be02b9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>40c5ecc8-bb8a-4fc4-98c4-415b9715b91f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> css-qqgp34-indicatorContainer</value>
      <webElementGuid>c8a43bfd-8a2a-472f-b695-c7903169a1cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Select-Annotation&quot;)/div[@class=&quot;css-71ak3d-control&quot;]/div[@class=&quot;css-1wy0on6&quot;]/div[@class=&quot;css-qqgp34-indicatorContainer&quot;]</value>
      <webElementGuid>4abc0ab4-b8cb-4d70-8daf-1bfa4ddcef8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Select-Annotation']/div/div[2]/div</value>
      <webElementGuid>2fe3f420-0204-46d2-9710-1bd55d20f46d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select'])[2]/following::div[5]</value>
      <webElementGuid>4ed2b978-ebb3-418a-8ef3-de67e45c1270</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Annotation Project*'])[1]/following::div[9]</value>
      <webElementGuid>08ad4980-f90d-4553-8f2c-8cca843fc0f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ANP1'])[1]/preceding::div[1]</value>
      <webElementGuid>73c83d31-e521-4547-b7f0-01d5782b672d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SUDO TEST'])[1]/preceding::div[2]</value>
      <webElementGuid>f1bc0e0c-a5fe-4345-956d-464a18bba8b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div[2]/div</value>
      <webElementGuid>5536e584-b0c3-4449-ac8b-26c318dfea1d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
