<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Select Workflow</name>
   <tag></tag>
   <elementGuidId>57b23182-c521-4500-bc44-163e7aae61dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.select__value-container.css-1hwfws3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='workflowModel']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>222121c3-b070-4ce4-ba5c-492afa16340d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select__value-container css-1hwfws3</value>
      <webElementGuid>d2d7ae17-ffa0-4292-a45d-4a77f407ac51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Workflow</value>
      <webElementGuid>32c195ba-d081-4338-b2e3-e9901235358e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;workflowModel&quot;)/div[@class=&quot;select__control select__control--is-focused select__control--menu-is-open css-dpzh99-control&quot;]/div[@class=&quot;select__value-container css-1hwfws3&quot;]</value>
      <webElementGuid>164398bb-3ef3-4ffb-aa3f-4cf683e59dc8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='workflowModel']/div/div</value>
      <webElementGuid>4ec2c4e9-301f-44dd-99e3-945168432781</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Workflow'])[1]/following::div[3]</value>
      <webElementGuid>493cf5f0-171a-4962-adfb-04c46defd5b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Project Description'])[1]/following::div[5]</value>
      <webElementGuid>417a4631-8c9a-4ac9-9079-611981772239</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='&lt;script>alert(1)&lt;/script>'])[5]/preceding::div[7]</value>
      <webElementGuid>3d3eda80-d3d4-4f25-9f8e-57f7e9d74e0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[3]/div/div/div/div</value>
      <webElementGuid>8257b2b4-a832-430a-a763-32dc6c5630ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Select Workflow' or . = 'Select Workflow')]</value>
      <webElementGuid>7eb2c7a3-80b1-4780-b8fd-fbe8bab95537</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
