<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_fabes  sudocarpl.ai</name>
   <tag></tag>
   <elementGuidId>237a97b2-4221-4352-b0a2-d16332e00a88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-2-option-4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#react-select-2-option-4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fb1dc380-3d0c-4710-a3b3-951a3d0b5840</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> css-1kw004b-option</value>
      <webElementGuid>baf705e9-94cb-4f10-9004-12d5488af23e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-2-option-4</value>
      <webElementGuid>0fe57272-c2dc-4967-a806-0e655f95611f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>6904afbc-6da8-42b1-bb7b-13c522374eb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>fabes : sudo@carpl.ai</value>
      <webElementGuid>add7b677-6c11-4480-b2d2-ad606f5131fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-2-option-4&quot;)</value>
      <webElementGuid>d0730b72-a838-4f05-b251-3a4fc7aa0d6b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-2-option-4']</value>
      <webElementGuid>482c5925-ab12-4026-b692-859a4a017592</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Select-Template']/div[2]/div/div[5]</value>
      <webElementGuid>f6e84dec-7d4d-45b0-b439-74d30a092204</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='fagman : sudo@carpl.ai'])[1]/following::div[1]</value>
      <webElementGuid>1adac1e9-8f40-4e1b-bbc8-d01a6b8f10aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SAGEMAKER TEMPLATE : sudo@carpl.ai'])[1]/following::div[2]</value>
      <webElementGuid>8b980515-7e91-4533-90af-1c9990178281</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test13 : sudo@carpl.ai'])[1]/preceding::div[1]</value>
      <webElementGuid>993fd083-2380-47ac-bf54-1b6b0a891475</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test12 : sudo@carpl.ai'])[1]/preceding::div[2]</value>
      <webElementGuid>b3a014ff-6991-48fc-a300-8b201033e58d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='fabes : sudo@carpl.ai']/parent::*</value>
      <webElementGuid>521f097d-6bbf-4dc3-acfc-ed3e674e684b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/div/div[5]</value>
      <webElementGuid>ab43e683-295f-416c-b9c0-205cf1c1ca82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-2-option-4' and (text() = 'fabes : sudo@carpl.ai' or . = 'fabes : sudo@carpl.ai')]</value>
      <webElementGuid>86c5fdb0-585a-4a22-bfed-22698dbf5785</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
