<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Create WorkflowProject NameProject Desc_4d88ee</name>
   <tag></tag>
   <elementGuidId>f4ee2483-da5e-424c-a8d3-706c2714c1c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0cbfdf99-54a9-47b1-84cf-3349497fe6b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> right-controlPanel full show </value>
      <webElementGuid>dc065658-3784-4faf-a531-4da1519e2863</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×Create WorkflowProject Name*Project DescriptionSelect WorkflowSelect WorkflowCreate Project</value>
      <webElementGuid>f60810d8-1763-4f90-b747-f8d14e9d967d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;wrapper appSection&quot;]/div[@class=&quot;content-wrapper&quot;]/div[1]/div[@class=&quot;main-content-inner&quot;]/div[@class=&quot;right-controlPanel full show&quot;]</value>
      <webElementGuid>b6ea4d0e-2def-43a1-ad7c-5c7ee33d9a2c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[4]</value>
      <webElementGuid>61ba9b19-dc0e-49d0-b27e-3d207f9981e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Workflow'])[12]/following::div[2]</value>
      <webElementGuid>ac508d25-b591-4434-b714-6c524552a177</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Workflow Category'])[12]/following::div[4]</value>
      <webElementGuid>c5f727ec-1069-4a5a-a0d3-0249eda68d24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]</value>
      <webElementGuid>056e0108-d798-45c0-bbbf-83ff32dbbe93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '×Create WorkflowProject Name*Project DescriptionSelect WorkflowSelect WorkflowCreate Project' or . = '×Create WorkflowProject Name*Project DescriptionSelect WorkflowSelect WorkflowCreate Project')]</value>
      <webElementGuid>2d461201-5c91-4512-8da6-7ef35a64bf8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
