<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_View TemplateUpload Annotations FormUpl_c1a3cb</name>
   <tag></tag>
   <elementGuidId>787c8715-db9f-4f9d-8dfd-cd78349090ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[@id='root']/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/span[1]/div[1]/div[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;root&quot;)/div[@class=&quot;wrapper appSection&quot;]/div[@class=&quot;content-wrapper&quot;]/div[1]/div[@class=&quot;projectselct&quot;]/div[@class=&quot;allprojectlist&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-25&quot;]/div[@class=&quot;projectitem&quot;]/span[1]/div[@class=&quot;dropdown-container&quot;][count(. | //xpath[(text() = 'View TemplateUpload Annotations FormUpload Annotations ROIAssign AnnotationsAdd ReviewerDownloadEdit ProjectDelete Project' or . = 'View TemplateUpload Annotations FormUpload Annotations ROIAssign AnnotationsAdd ReviewerDownloadEdit ProjectDelete Project')]) = count(//xpath[(text() = 'View TemplateUpload Annotations FormUpload Annotations ROIAssign AnnotationsAdd ReviewerDownloadEdit ProjectDelete Project' or . = 'View TemplateUpload Annotations FormUpload Annotations ROIAssign AnnotationsAdd ReviewerDownloadEdit ProjectDelete Project')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View TemplateUpload Annotations FormUpload Annotations ROIAssign AnnotationsAdd ReviewerDownloadEdit ProjectDelete Project</value>
      <webElementGuid>19edaf59-7a29-4489-8573-739bdcf454df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>xpath</value>
      <webElementGuid>059385b9-37f3-4814-94c2-fe7b5063c7e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-container</value>
      <webElementGuid>69dcd007-21f3-4a63-8d17-39ccc48e8ec5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//body/div[@id='root']/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/span[1]/div[1]/div[1]</value>
      <webElementGuid>0a667893-9f27-4ca4-87b0-9222aa2ae111</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/div/div[2]/div/span/div</value>
      <webElementGuid>00258081-240c-475f-8c36-a7d7353dea0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Annotate'])[1]/following::div[3]</value>
      <webElementGuid>0a8181ef-0bbc-4cfa-b996-213f843ef6ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Update'])[1]/following::div[5]</value>
      <webElementGuid>b37aa416-5c8f-4198-baec-a804643401ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span/div</value>
      <webElementGuid>e69e5a36-261f-493f-8eab-f86dfd4ede5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'View TemplateUpload Annotations FormUpload Annotations ROIAssign AnnotationsAdd ReviewerDownloadEdit ProjectDelete Project' or . = 'View TemplateUpload Annotations FormUpload Annotations ROIAssign AnnotationsAdd ReviewerDownloadEdit ProjectDelete Project')]</value>
      <webElementGuid>51e162fb-9a66-467b-9539-43805b71b549</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/div/div/div/span/div</value>
      <webElementGuid>b8e89a21-328d-4af6-922b-75de722d958a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create Project'])[1]/following::div[5]</value>
      <webElementGuid>bcf386ab-9140-4109-bcd3-c0acf30e0be7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div</value>
      <webElementGuid>087b6e4a-1577-41e0-b6ec-5da92ea25032</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
