<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_fuzzy  sudocarpl.ai</name>
   <tag></tag>
   <elementGuidId>887ab94f-3db4-46cc-8dbe-971c868af835</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-4-option-6']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#react-select-4-option-6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>39bd123d-5317-4c9d-b1a3-5ea9a1d371ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> css-1kw004b-option</value>
      <webElementGuid>c476ba54-9844-4705-a263-cad624b7429b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-4-option-6</value>
      <webElementGuid>9de98084-20b6-4154-942b-f11841f42819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>b9e52476-875b-4396-b72f-29337a5edda6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>fuzzy : sudo@carpl.ai</value>
      <webElementGuid>f6d5d13e-05e8-48a3-ab9f-4fbc351e4b96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-4-option-6&quot;)</value>
      <webElementGuid>dde143c5-6dba-46d2-9bc2-476d1f453ffd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-4-option-6']</value>
      <webElementGuid>9337f721-d349-40c9-b4d9-bb4453827a0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Select-dataset']/div[2]/div/div[7]</value>
      <webElementGuid>ce34fa88-50eb-46d8-b22c-69e3a8043cb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TEST@5 : sudo@carpl.ai'])[1]/following::div[1]</value>
      <webElementGuid>ef505843-e3b3-46f7-9b06-247cbb488be8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='xray mini kaggle : sudo@carpl.ai'])[1]/following::div[2]</value>
      <webElementGuid>ed087006-6e32-4792-8a16-dfb4b6e7491a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Testttt : sudo@carpl.ai'])[1]/preceding::div[1]</value>
      <webElementGuid>2a53cd56-bcf1-473a-bf2d-b5d7e30b4b33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='kaggle chest xrays : sudo@carpl.ai'])[1]/preceding::div[2]</value>
      <webElementGuid>8349282b-dbdf-4e24-b19a-25496d1d6ec9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='fuzzy : sudo@carpl.ai']/parent::*</value>
      <webElementGuid>5acfa086-f11c-4210-aa8b-8bf2dd643de7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div[7]</value>
      <webElementGuid>360bfa62-766a-46c6-a0f4-bf41aec5ef6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-4-option-6' and (text() = 'fuzzy : sudo@carpl.ai' or . = 'fuzzy : sudo@carpl.ai')]</value>
      <webElementGuid>fb4a5f1b-62f0-4951-aad0-1410aa2b3398</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
