<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_RESET PASSWORDEnter your registered ema_142057</name>
   <tag></tag>
   <elementGuidId>a2a2040b-067c-423d-8c44-9b6e5608b80c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='preloader']/div[2]/div/div/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.loginwrap</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>05cdf9ed-5dcb-46e8-b64b-b4b7911bc3dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>loginwrap</value>
      <webElementGuid>dab5e656-bdd2-42e0-bf1d-eb13cc6feafa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>RESET PASSWORDEnter your registered email address to initiate the password reset process.RESET PASSWORD </value>
      <webElementGuid>5de6a26b-8e0d-4aef-bca7-271727d3cd3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;preloader&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;loginpge&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-sm-6 col-md-6 col-lg-6	col-xl-6 col col&quot;]/div[1]/div[@class=&quot;loginwrap&quot;]</value>
      <webElementGuid>5d41ed77-dfdd-45ad-afea-2b21da4c5c3f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='preloader']/div[2]/div/div/div[2]/div/div</value>
      <webElementGuid>b6c8837c-690f-4066-80e3-2a20076a562f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div</value>
      <webElementGuid>94b26319-9627-4bbd-80ea-879586cf370b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'RESET PASSWORDEnter your registered email address to initiate the password reset process.RESET PASSWORD ' or . = 'RESET PASSWORDEnter your registered email address to initiate the password reset process.RESET PASSWORD ')]</value>
      <webElementGuid>2c8e8158-28ce-441b-baf3-a0ea737f040d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
