<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_newGw  sudocarpl.ai</name>
   <tag></tag>
   <elementGuidId>a23c9ebc-c7e1-4f7c-b82c-c1847d638f5f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-4-option-12']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#react-select-4-option-12</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2043b979-bc3a-4b7e-a4ed-cf221d31c887</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> css-1kw004b-option</value>
      <webElementGuid>9508cfae-8903-4070-881a-9f52ed2fceab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-4-option-12</value>
      <webElementGuid>2fb91782-03ef-4bda-9fa8-4d07602e5b54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>a36bea12-6466-4f41-9755-c2119d2efaf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>newGw : sudo@carpl.ai</value>
      <webElementGuid>49274857-03d5-4158-b65e-1687339f5d86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-4-option-12&quot;)</value>
      <webElementGuid>4f22ade5-0f11-41e0-a989-09c4e8e89dc4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-4-option-12']</value>
      <webElementGuid>c5c98c2e-c8c9-4af1-9a68-db99e80a9821</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Select-dataset']/div[2]/div/div[13]</value>
      <webElementGuid>76e8db17-6f79-4956-9327-3c8a38685a2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NEWGW : sashakta.singh@carpl.ai'])[1]/following::div[1]</value>
      <webElementGuid>405bbc3b-49d3-42f8-8d03-8e4c804c84c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='gateway : sashakta.singh@carpl.ai'])[1]/following::div[2]</value>
      <webElementGuid>310af3db-500b-44f0-846b-b60033bc9f21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Demotest : sudo@carpl.ai'])[1]/preceding::div[1]</value>
      <webElementGuid>55214bc1-12dd-431c-88d0-aba0b1da54e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dataset_4 : sudo@carpl.ai'])[1]/preceding::div[2]</value>
      <webElementGuid>d373d487-6947-48cc-8d99-225c13abd9fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='newGw : sudo@carpl.ai']/parent::*</value>
      <webElementGuid>a49bd279-7ad1-4d0e-9323-2712b56dccd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div[13]</value>
      <webElementGuid>6df114da-a3c2-4d0b-b9ad-406540601f84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-4-option-12' and (text() = 'newGw : sudo@carpl.ai' or . = 'newGw : sudo@carpl.ai')]</value>
      <webElementGuid>026accc7-6d5f-4bfe-8e2d-0bd2bc26352f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
