<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Create Dataset</name>
   <tag></tag>
   <elementGuidId>ef74a2ee-12f2-4bfe-9113-b2e761760ab4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.modal-footer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='createDatasetForm']/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fe56aa5c-9e22-4328-9193-332ac99dc953</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-footer</value>
      <webElementGuid>819002f1-2e44-408c-913a-6a0fb4c887ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create Dataset</value>
      <webElementGuid>b3e8c74a-fea5-43c0-93d3-edf98f62c85e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;createDatasetForm&quot;)/div[@class=&quot;modal-body&quot;]/div[@class=&quot;modal-footer&quot;]</value>
      <webElementGuid>e902f04e-a8d5-40ce-a4d0-30073e76552a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='createDatasetForm']/div/div[2]</value>
      <webElementGuid>2bba0ef5-3aa4-4fd2-a19e-9f84df94f664</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Modality'])[1]/following::div[6]</value>
      <webElementGuid>a1631647-4f41-48db-a477-249cfffc3ef5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose Modality'])[1]/following::div[10]</value>
      <webElementGuid>4b36d9b7-898e-4de0-a87f-ebf91c55a83e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]</value>
      <webElementGuid>f3be9c48-8034-4d89-becf-d2da2b2ce6f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Create Dataset' or . = 'Create Dataset')]</value>
      <webElementGuid>3d51ef05-2c7d-45db-a0b2-1a602e4d5448</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
