<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form_Register Enter NameRegisterAlready Reg_ef0c89</name>
   <tag></tag>
   <elementGuidId>546cc561-26bb-49cb-b4b0-488d20d12575</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#registerForm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='registerForm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>d9cfe7e1-df7e-48b0-ad17-bde13de8adaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>registerForm</value>
      <webElementGuid>8859dba2-048e-4951-bf44-724503119bd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>method</name>
      <type>Main</type>
      <value>post</value>
      <webElementGuid>9d4deb4c-15dc-49e4-8bf7-b04cdb0f6aa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a3dfc84b-088a-4aa8-aa85-5516f7ebca2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Register Enter NameRegisterAlready Registered? LOG IN</value>
      <webElementGuid>1198083c-dc96-4255-bfb9-5f45d738fade</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registerForm&quot;)</value>
      <webElementGuid>3fde2896-1981-4a4a-946e-4a2e976cb394</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//form[@id='registerForm']</value>
      <webElementGuid>fb93502f-b4e4-44cb-bc90-3214eec1ca2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='preloader']/div[2]/div/div/div[2]/div/div/form</value>
      <webElementGuid>d57710b2-c797-4615-860a-388c96193ab5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form</value>
      <webElementGuid>27fa1a98-eeff-46df-9c8c-2aeed5846fdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//form[@id = 'registerForm' and (text() = 'Register Enter NameRegisterAlready Registered? LOG IN' or . = 'Register Enter NameRegisterAlready Registered? LOG IN')]</value>
      <webElementGuid>8c98c78e-ad15-4f71-b913-ca323a7538ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
