<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form_Login in to CARPL Enter UsernameLOG IN_8eda57</name>
   <tag></tag>
   <elementGuidId>6728de0d-b9b2-4615-8827-ef9194e2bcdc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#login_form</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='login_form']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>a2402965-e904-4a89-85a2-a8f3dd65da18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login_form</value>
      <webElementGuid>2b72a582-de1b-46fc-81c1-6045fd1789ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>method</name>
      <type>Main</type>
      <value>post</value>
      <webElementGuid>17f87cfd-1f66-42a1-aeb1-10e7e483dddd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8c464c5e-3eed-453b-8ef0-842682ed1b46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login in to CARPL Enter UsernameLOG INForgot your password? Click here to reset itNew user? Click here to register</value>
      <webElementGuid>31e5f266-314a-44be-a013-ea5696ac8b4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login_form&quot;)</value>
      <webElementGuid>a2af6c82-bf10-43e1-bc21-6925bd4138f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>d06ae436-effd-4109-824b-81bcb671e3dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login_form</value>
      <webElementGuid>ad4b573c-0638-4bd7-a559-f44c8b4d4634</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>method</name>
      <type>Main</type>
      <value>post</value>
      <webElementGuid>e21bbdad-d027-41e2-be54-f7beb0748c09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4c69c983-d98b-4293-b297-7e809bf9311c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login in to CARPL Enter UsernameLOG INForgot your password? Click here to reset itNew user? Click here to register</value>
      <webElementGuid>758bbc97-4d04-4c2a-b5dc-7d45ba7ce053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login_form&quot;)</value>
      <webElementGuid>cf8efc06-452e-4eb3-9c09-0cbf985b2d74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>cfd998a8-7cf8-4bd9-a578-8bac9aad4ec5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login_form</value>
      <webElementGuid>c593c9ec-c6a2-408d-a19c-4c9ac6517387</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>method</name>
      <type>Main</type>
      <value>post</value>
      <webElementGuid>7c5c2bb2-08d1-4072-b55c-d1d09173dae5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1df1e9d4-be8a-474a-b77a-b1f6e7619b9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login in to CARPL Enter UsernameLOG INForgot your password? Click here to reset itNew user? Click here to register</value>
      <webElementGuid>afdded20-af30-4801-93d3-e9c5f413da64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login_form&quot;)</value>
      <webElementGuid>1e311b66-cfa3-4906-900a-b224d22c7030</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//form[@id='login_form']</value>
      <webElementGuid>3043000d-ec85-4bc5-8097-9275b8092a12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='preloader']/div[2]/div/div/div[2]/div/div/form</value>
      <webElementGuid>3eda966d-c99e-43ab-abfa-14929dbc535d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form</value>
      <webElementGuid>f29b7d6f-8b8d-41d3-af22-2b1e2aaafbc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//form[@id = 'login_form' and (text() = 'Login in to CARPL Enter UsernameLOG INForgot your password? Click here to reset itNew user? Click here to register' or . = 'Login in to CARPL Enter UsernameLOG INForgot your password? Click here to reset itNew user? Click here to register')]</value>
      <webElementGuid>df5bf5d5-b421-4a26-a73b-b4b1fed85e77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
