<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form_Register Enter Name Enter Email IDRegi_ba56d3</name>
   <tag></tag>
   <elementGuidId>5ef3194b-959e-4f29-96a3-97ec590aaf50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#registerForm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='registerForm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>81fc05cf-c68d-40e8-8f6d-edc5f9bb0ab1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>registerForm</value>
      <webElementGuid>58aab482-ade2-4ff3-97aa-2309b26bba17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>method</name>
      <type>Main</type>
      <value>post</value>
      <webElementGuid>a803dfd0-4321-473b-85e8-e4948005edb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c83e05f1-6f2d-4a65-a765-63c96a900cbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Register Enter Name Enter Email IDRegisterAlready Registered? LOG IN</value>
      <webElementGuid>1106fcca-b50b-4497-b457-642fb4629a1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registerForm&quot;)</value>
      <webElementGuid>d6813114-8c97-4e1b-94d4-570fab100e25</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//form[@id='registerForm']</value>
      <webElementGuid>6cc12162-816c-448f-9b41-e2601a19bc31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='preloader']/div[2]/div/div/div[2]/div/div/form</value>
      <webElementGuid>622a888a-663b-42d4-bd9b-d1f01702a419</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form</value>
      <webElementGuid>dd981eeb-2cb6-452f-adc5-b5a9f96cd3bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//form[@id = 'registerForm' and (text() = 'Register Enter Name Enter Email IDRegisterAlready Registered? LOG IN' or . = 'Register Enter Name Enter Email IDRegisterAlready Registered? LOG IN')]</value>
      <webElementGuid>fb4e0201-956f-4236-bc93-4b8c5b589eca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
