<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form_Register Enter Name Enter Email ID Ent_e30a4c</name>
   <tag></tag>
   <elementGuidId>2c14babb-dcdc-4d46-a607-ed516e6990a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#registerForm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='registerForm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>d100e69e-2758-4b3a-882d-927837bf0de4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>registerForm</value>
      <webElementGuid>203e51c3-2bb6-476c-b596-cb5866431875</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>method</name>
      <type>Main</type>
      <value>post</value>
      <webElementGuid>a8041a25-c608-4d8b-9ffe-43e98e7c1000</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d2706e33-bc12-4e89-9ffa-bf46767d77d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Register Enter Name Enter Email ID Enter PasswordRegisterAlready Registered? LOG IN</value>
      <webElementGuid>a4f761dd-79f1-4fc2-8f3f-c2df268edac2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registerForm&quot;)</value>
      <webElementGuid>7df68d78-8af7-452e-a6f5-478f83cd776e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//form[@id='registerForm']</value>
      <webElementGuid>74ec089b-c2a8-49f6-8df6-2484e8bb357d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='preloader']/div[2]/div/div/div[2]/div/div/form</value>
      <webElementGuid>7ffb725e-e903-4316-9ccc-1204705f6e4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form</value>
      <webElementGuid>72a44a3d-3c86-40fb-87b7-a829e1676ca7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//form[@id = 'registerForm' and (text() = 'Register Enter Name Enter Email ID Enter PasswordRegisterAlready Registered? LOG IN' or . = 'Register Enter Name Enter Email ID Enter PasswordRegisterAlready Registered? LOG IN')]</value>
      <webElementGuid>efe79094-215d-470a-94a5-1dbdfbf7a21b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
