<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form_Login in to CARPL Enter Username Enter_0b81a2</name>
   <tag></tag>
   <elementGuidId>167f4cca-ee5a-4e87-996e-fe0ef978a837</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#login_form</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='login_form']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>190dd507-55cf-4033-98b7-d0ea0da4976a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login_form</value>
      <webElementGuid>30ddb0fd-4120-4e0e-9ec5-9cd526dbfc81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>method</name>
      <type>Main</type>
      <value>post</value>
      <webElementGuid>c1e3de9a-7f78-42e3-9152-4e7afdafd7a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1e1b3088-b462-46d9-8536-d17c55c0fa54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login in to CARPL Enter Username Enter PasswordLOG INForgot your password? Click here to reset itNew user? Click here to register</value>
      <webElementGuid>8e1ca4f9-9467-4fe3-b8cb-38b4aa2f5bd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login_form&quot;)</value>
      <webElementGuid>2485de48-5ab9-461f-b72b-9b27ac7fc4f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//form[@id='login_form']</value>
      <webElementGuid>eda251c0-5459-437f-891e-89dc9c934277</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='preloader']/div[2]/div/div/div[2]/div/div/form</value>
      <webElementGuid>07f6c488-c628-45cd-bd7e-a624a6f9ce44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form</value>
      <webElementGuid>bb72e867-16c1-4688-9bfb-c843dd021d37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//form[@id = 'login_form' and (text() = 'Login in to CARPL Enter Username Enter PasswordLOG INForgot your password? Click here to reset itNew user? Click here to register' or . = 'Login in to CARPL Enter Username Enter PasswordLOG INForgot your password? Click here to reset itNew user? Click here to register')]</value>
      <webElementGuid>6c07aad8-7d74-4883-9921-688a6183b74b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
