<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form_Register Password should have 8-20 cha_a3cfa4</name>
   <tag></tag>
   <elementGuidId>1e690422-6781-40c1-9bc9-8aa708ffe7fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='registerForm']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#registerForm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>5292b0e3-c2cd-4819-b36f-4479c39e9358</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>registerForm</value>
      <webElementGuid>6b5b2d09-2ae8-4ed8-8365-b8fa329ceab5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>method</name>
      <type>Main</type>
      <value>post</value>
      <webElementGuid>bcb397cb-59a4-4faa-a198-30da9de0c293</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b9e91b34-a43f-4fd7-8a32-fe2c7af8d564</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Register Password should have 8-20 characters comprising letters, atleast one uppercase letter, one lower case letter, one number and one special character[!*^$@#%&amp;()]RegisterAlready Registered? LOG IN</value>
      <webElementGuid>eb8234a7-b53e-43d4-81da-e90c5c74b3d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registerForm&quot;)</value>
      <webElementGuid>59434393-095c-4973-85ef-160aca196cbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>2f04e343-2dd8-48ad-acb0-89ef22d5bd07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>registerForm</value>
      <webElementGuid>0d57fedd-9a05-4bfa-a15b-92a024cfbc7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>method</name>
      <type>Main</type>
      <value>post</value>
      <webElementGuid>c918a9c0-042f-44b4-9d01-7a8d0384f9c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>91c68c64-e47d-4217-ab5a-6d00cba3ff95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Register Password should have 8-20 characters comprising letters, atleast one uppercase letter, one lower case letter, one number and one special character[!*^$@#%&amp;()]RegisterAlready Registered? LOG IN</value>
      <webElementGuid>48175559-2b66-49ca-ad4a-e654c9b00e83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registerForm&quot;)</value>
      <webElementGuid>013c42d4-2218-4c03-bc17-3ccc6b5ebd77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>0da1eb7c-1638-40aa-a416-5a217b27af11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>registerForm</value>
      <webElementGuid>e6b88aea-a2c5-4d04-8446-f57d311faa4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>method</name>
      <type>Main</type>
      <value>post</value>
      <webElementGuid>b9150be8-901a-4e92-8bb1-652dfa32c33d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4ab8ec2d-8027-4496-833d-fc7fdaf075d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Register Password should have 8-20 characters comprising letters, atleast one uppercase letter, one lower case letter, one number and one special character[!*^$@#%&amp;()]RegisterAlready Registered? LOG IN</value>
      <webElementGuid>d774a754-f36b-4fe8-a44b-aa42976bbafd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registerForm&quot;)</value>
      <webElementGuid>03d2d096-c2ec-4414-8a93-f9a1fd0e492e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>e64c86fa-85ad-420f-904a-4d3714580b4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>registerForm</value>
      <webElementGuid>f00c1244-3f17-4925-b685-1171fe4e2104</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>method</name>
      <type>Main</type>
      <value>post</value>
      <webElementGuid>78e6295e-1065-4b58-afc8-64c728b34060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5efa4866-5706-43b8-b22e-df1b7e91615f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Register Password should have 8-20 characters comprising letters, atleast one uppercase letter, one lower case letter, one number and one special character[!*^$@#%&amp;()]RegisterAlready Registered? LOG IN</value>
      <webElementGuid>28b1d246-7676-48a9-98d2-d6070f13d172</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registerForm&quot;)</value>
      <webElementGuid>6a00d9ba-37a7-4276-9ca9-df28ba6bc730</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>546ce860-bee7-4eb4-b7bc-1d5681959958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>registerForm</value>
      <webElementGuid>fc22bc2d-a682-4302-be0f-71fcc0b5807c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>method</name>
      <type>Main</type>
      <value>post</value>
      <webElementGuid>90a7f73b-3382-4404-96e5-3fb4cc745bed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0514188a-5966-4e32-9abd-662cb0c210c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Register Password should have 8-20 characters comprising letters, atleast one uppercase letter, one lower case letter, one number and one special character[!*^$@#%&amp;()]RegisterAlready Registered? LOG IN</value>
      <webElementGuid>0b1c3c02-da62-4005-b9a2-edecd2f629f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registerForm&quot;)</value>
      <webElementGuid>fd77444e-f550-4797-bc8b-ac6fbd18fc32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>6bfb56db-c046-4d0e-a701-d9e2bd724a2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>registerForm</value>
      <webElementGuid>57d36bcd-1e70-4d79-b4c4-21f18b07105d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>method</name>
      <type>Main</type>
      <value>post</value>
      <webElementGuid>563ed6d2-6068-4708-a423-5fcfe63dfa5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f3cb5d78-f273-4a28-aa89-b0532a5fb412</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Register Password should have 8-20 characters comprising letters, atleast one uppercase letter, one lower case letter, one number and one special character[!*^$@#%&amp;()]RegisterAlready Registered? LOG IN</value>
      <webElementGuid>fffc8032-766b-45a1-b5e9-f99b7cccb211</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registerForm&quot;)</value>
      <webElementGuid>44b74da0-11d1-49ee-a5b2-8f0b169488ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>89a7cd39-83c0-4e6e-a0b2-310a5912bb69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>registerForm</value>
      <webElementGuid>9a467aa7-74a1-436d-9078-472197ae316b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>method</name>
      <type>Main</type>
      <value>post</value>
      <webElementGuid>b13533ac-e2ea-4115-9cef-9d0e476a4b43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>32d2572b-e248-4e18-9b01-b06dcfa79642</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Register Password should have 8-20 characters comprising letters, atleast one uppercase letter, one lower case letter, one number and one special character[!*^$@#%&amp;()]RegisterAlready Registered? LOG IN</value>
      <webElementGuid>fe7181cf-2b4b-4aa7-bec9-39869ab01e9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registerForm&quot;)</value>
      <webElementGuid>34ec634b-fc71-4f47-8574-5b001d5751e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//form[@id='registerForm']</value>
      <webElementGuid>c96d0847-759f-4ac8-bf89-23b08c7aa046</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='preloader']/div[2]/div/div/div[2]/div/div/form</value>
      <webElementGuid>70c6ff18-5ec2-406a-b7d0-9e99045e8944</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form</value>
      <webElementGuid>7b807ef9-788c-4c26-bcf4-0238874c7094</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//form[@id = 'registerForm' and (text() = 'Register Password should have 8-20 characters comprising letters, atleast one uppercase letter, one lower case letter, one number and one special character[!*^$@#%&amp;()]RegisterAlready Registered? LOG IN' or . = 'Register Password should have 8-20 characters comprising letters, atleast one uppercase letter, one lower case letter, one number and one special character[!*^$@#%&amp;()]RegisterAlready Registered? LOG IN')]</value>
      <webElementGuid>13079d5f-7a15-487d-aef9-b8a9f032faa4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
