<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form_RESET PASSWORDEnter New Password Enter_177522</name>
   <tag></tag>
   <elementGuidId>49b43e9f-1d15-4efb-9f58-b63457a5b3f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='password-reset']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#password-reset</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>999c3b0e-4f4b-44f9-ab78-1639e903876b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>forgotEnterPassword </value>
      <webElementGuid>5d8de996-b239-4964-96ce-e3ffb453702d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>password-reset</value>
      <webElementGuid>1f7989fb-5b3e-4b9f-9c1e-8b7e511f92e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>method</name>
      <type>Main</type>
      <value>post</value>
      <webElementGuid>e2779f6e-1c73-4bd6-88fd-8c43c84d6fc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>012eb718-84ec-435e-866c-6a6ab1cdf031</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>RESET PASSWORDEnter New Password Enter PasswordRESET PASSWORDClick here to LOG IN</value>
      <webElementGuid>fbe3cceb-c77f-4bec-a964-e9487fbed073</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;password-reset&quot;)</value>
      <webElementGuid>fe44eed5-8377-461a-8f43-139eac720a40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>86722eb2-43ef-4d84-8ae5-c280addc2da1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>forgotEnterPassword </value>
      <webElementGuid>b7b47778-b7a0-43a1-909e-61e16232e341</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>password-reset</value>
      <webElementGuid>c8812331-9c2e-40b4-9cb9-e4def2bdf4e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>method</name>
      <type>Main</type>
      <value>post</value>
      <webElementGuid>ff22c02e-736b-4545-9863-2480851b6ab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1319b041-2821-47fc-a1ac-87766c08a9f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>RESET PASSWORDEnter New Password Enter PasswordRESET PASSWORDClick here to LOG IN</value>
      <webElementGuid>9c31439b-d52c-4fbe-aa22-f31a632552af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;password-reset&quot;)</value>
      <webElementGuid>dc595726-e9aa-4270-95a6-a3c882af3c12</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//form[@id='password-reset']</value>
      <webElementGuid>a39533a5-7dcf-4645-a89f-9e50cd04667d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='preloader']/div[2]/div/div/div[2]/div/div/form</value>
      <webElementGuid>ef3e2a38-4b07-4702-a030-4f2266ecda27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form</value>
      <webElementGuid>f88967db-d9c0-4f50-9172-f1ff1684a858</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//form[@name = 'forgotEnterPassword ' and @id = 'password-reset' and (text() = 'RESET PASSWORDEnter New Password Enter PasswordRESET PASSWORDClick here to LOG IN' or . = 'RESET PASSWORDEnter New Password Enter PasswordRESET PASSWORDClick here to LOG IN')]</value>
      <webElementGuid>16276a8b-80df-408c-8c60-9e4263f8956f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
