<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Dropdown_fa fa-edit mr-3 fa_template</name>
   <tag></tag>
   <elementGuidId>768c120b-fe8d-4342-a923-f4f9b9ce8a8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div[2]/div/div/div/div[3]/div[2]/div/div/span[5]/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-edit.mr-3.fa_template</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>f795caec-d35a-4ab7-aedb-784e71cf8c35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-edit mr-3 fa_template</value>
      <webElementGuid>1d96fb52-4a90-4be1-8990-0ef7019ef518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;wrapper appSection&quot;]/div[@class=&quot;content-wrapper&quot;]/div[1]/div[@class=&quot;App&quot;]/div[2]/div[@class=&quot;row mt-3&quot;]/div[@class=&quot;col-md-8 template_builder&quot;]/div[@class=&quot;mt-3&quot;]/div[3]/div[@class=&quot;bg-template_default&quot;]/div[@class=&quot;list-group-item mb-1 bg-template_items preview_item&quot;]/div[1]/span[@class=&quot;float-right onHover&quot;]/i[@class=&quot;fa fa-edit mr-3 fa_template&quot;]</value>
      <webElementGuid>f0c8e2da-d13a-4c30-9ecf-d93dcdafcf14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>0b69eb42-f8d3-4a1c-b314-d90883db919c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-edit mr-3 fa_template</value>
      <webElementGuid>aeb3ecbf-160c-4d0e-a67f-ed2123dad950</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;wrapper appSection&quot;]/div[@class=&quot;content-wrapper&quot;]/div[1]/div[@class=&quot;App&quot;]/div[2]/div[@class=&quot;row mt-3&quot;]/div[@class=&quot;col-md-8 template_builder&quot;]/div[@class=&quot;mt-3&quot;]/div[3]/div[@class=&quot;bg-template_default&quot;]/div[@class=&quot;list-group-item mb-1 bg-template_items preview_item&quot;]/div[1]/span[@class=&quot;float-right onHover&quot;]/i[@class=&quot;fa fa-edit mr-3 fa_template&quot;]</value>
      <webElementGuid>8415839d-6b8d-4e96-9b1f-9f35fc78cdca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>d2d09b24-51be-46a3-8f87-448c3743a3e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-edit mr-3 fa_template</value>
      <webElementGuid>be763e8b-e0b7-4a12-9be4-6c71e342c3f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;wrapper appSection&quot;]/div[@class=&quot;content-wrapper&quot;]/div[1]/div[@class=&quot;App&quot;]/div[2]/div[@class=&quot;row mt-3&quot;]/div[@class=&quot;col-md-8 template_builder&quot;]/div[@class=&quot;mt-3&quot;]/div[3]/div[@class=&quot;bg-template_default&quot;]/div[@class=&quot;list-group-item mb-1 bg-template_items preview_item&quot;]/div[1]/span[@class=&quot;float-right onHover&quot;]/i[@class=&quot;fa fa-edit mr-3 fa_template&quot;]</value>
      <webElementGuid>8a030b39-c7ef-4b3f-a16d-c3d12bbdb6dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/div/div/div/div[3]/div[2]/div/div/span[5]/i</value>
      <webElementGuid>9b6b4354-642c-4a6f-b8cd-a6212a7e4a27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[5]/i</value>
      <webElementGuid>6bbedfb4-afbb-4d30-93a5-b177f547b7a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
