<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Register_togglePassword1</name>
   <tag></tag>
   <elementGuidId>698c66b4-c70f-4238-acd9-bc9a65b4f6b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#togglePassword1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='togglePassword1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>4558d6f1-2772-4bce-8e64-19b52fbb8e95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-eye</value>
      <webElementGuid>ac700219-92eb-4f29-9dfc-72e3beeb7111</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>togglePassword1</value>
      <webElementGuid>3b5303fa-92da-4fd7-a3a0-68704b0b2311</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;togglePassword1&quot;)</value>
      <webElementGuid>0c9d1404-aa16-40cf-84c7-8b2982aa1bcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>53274cf8-3da3-4523-9d80-ace9f1c89156</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-eye</value>
      <webElementGuid>ead7309a-75cc-4a10-a416-f18fb7d44c20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>togglePassword1</value>
      <webElementGuid>49295eda-95e8-4642-9d2f-01b7addd2947</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;togglePassword1&quot;)</value>
      <webElementGuid>6e10a86d-cfc3-4c7e-a08b-aadacdebc550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>0a57b3d6-35e9-4b23-94d6-b12f544063b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-eye</value>
      <webElementGuid>ff5ba7bd-200d-4c6c-a1b0-859065b0b198</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>togglePassword1</value>
      <webElementGuid>6eb2dd7a-b212-4a04-b839-3a4c87bf6773</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;togglePassword1&quot;)</value>
      <webElementGuid>4d921c62-c32d-419b-98a5-0114ac57cb32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='togglePassword1']</value>
      <webElementGuid>91713d5b-9f39-49af-9bdd-c54d5a0afe37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registerForm']/div[4]/i[2]</value>
      <webElementGuid>ebdf1ad3-035e-4d71-a604-da1a5e17bc5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i[2]</value>
      <webElementGuid>28e4f139-4c50-4f27-8a19-5191eea6bd8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'togglePassword1']</value>
      <webElementGuid>9a5115b1-e0ea-48ca-a6a1-5399ae4a1eb7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
