<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_ROI Labels_fa fa-info-circle</name>
   <tag></tag>
   <elementGuidId>2a00eeae-5a28-41ad-922d-9b9f8d59cdc6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div[2]/div/div/div/label/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-info-circle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>ec013211-4366-4b87-b714-f784660903ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-info-circle</value>
      <webElementGuid>4fe73046-3957-4110-a50e-07bdb2783c22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d9a832a4-d238-4efc-a526-cc069c0e07b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tip</name>
      <type>Main</type>
      <value>ROI labels are labels which the user&lt;br /> can choose as they  go about creating annotation &lt;br /> ROIs on CARPL's Dicom Viewer. Use this for &lt;br /> pixel level annotations and / or bounding boxes.</value>
      <webElementGuid>49d2c538-b78f-4aaf-b6fb-8ae57f0e0658</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-for</name>
      <type>Main</type>
      <value>ROILabels</value>
      <webElementGuid>03313604-6224-44f6-a6f4-04429d7f3485</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>currentitem</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>43bbaa9f-88d6-44c4-b83f-ca76fbb1f751</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>ROILabels</value>
      <webElementGuid>aab55101-4808-45ab-9bfc-74662e9b05af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;wrapper appSection&quot;]/div[@class=&quot;content-wrapper&quot;]/div[1]/div[@class=&quot;App&quot;]/div[2]/div[@class=&quot;row mt-3&quot;]/div[@class=&quot;col-md-8 template_builder&quot;]/div[@class=&quot;mt-3&quot;]/label[1]/i[@class=&quot;fa fa-info-circle&quot;]</value>
      <webElementGuid>721ddd46-0a58-4907-b33b-99add12db2d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/div/div/div/label/i</value>
      <webElementGuid>4bf8ec19-95af-4c90-affd-a7333ef9d202</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/i</value>
      <webElementGuid>ef6b0ff6-2e43-49e8-8b97-ff0f6f77896f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
