<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_WorkFlow_Icon-datasetManager</name>
   <tag></tag>
   <elementGuidId>cb890e2c-f773-407d-942f-889018e7651f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='configuration']/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.Icon-datasetManager</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>87fc88ba-3572-4470-8c88-6db2807fc6f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Icon-datasetManager</value>
      <webElementGuid>d67e2e37-9457-4195-9597-f70b2f07e22c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fea1d47f-32d5-49ec-b3ca-5c10099cffb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;configuration&quot;)/a[1]/i[@class=&quot;Icon-datasetManager&quot;]</value>
      <webElementGuid>34a623db-e39d-4fd7-94b9-63c57c96f729</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='configuration']/a/i</value>
      <webElementGuid>34ca79e4-03ea-4ff3-b065-873e211774a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a/i</value>
      <webElementGuid>7f058626-0427-43ad-b1a3-c1a0aeffcdcd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
