<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Dashboard_img-fluid rounded-circle shadow full</name>
   <tag></tag>
   <elementGuidId>48d2283b-0c3a-48e9-910e-caf4af8cb676</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.img-fluid.rounded-circle.shadow.full</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[@id='userInfo']/img)[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>38ef6ddd-b395-4b68-b529-b143fac92673</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/user.png</value>
      <webElementGuid>e66670a4-81c7-433b-8da1-f8cf0a2a2f74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-fluid rounded-circle shadow full</value>
      <webElementGuid>c4a723f9-d6c8-4206-81a0-c890ac3f6ef3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tip</name>
      <type>Main</type>
      <value>admin</value>
      <webElementGuid>51dbc4a1-092a-45a8-a8bd-dfa413af6995</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-for</name>
      <type>Main</type>
      <value>admin</value>
      <webElementGuid>d245596b-eebc-40ac-8fe3-872664b024d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>currentitem</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d869c9e6-f78d-44ca-a4f8-4980791d245d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>admin</value>
      <webElementGuid>f31e3bb5-dd62-4e82-a145-17b23a3021dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;wrapper appSection&quot;]/div[@class=&quot;content-wrapper&quot;]/header[@class=&quot;main-header shadow&quot;]/nav[@class=&quot;navbar navbar-static-top&quot;]/ul[@class=&quot;ml-auto d-flex align-items-center list-unstyled mb-0 headerUser&quot;]/li[@class=&quot;nav-item ml-auto user&quot;]/a[@id=&quot;userInfo&quot;]/img[@class=&quot;img-fluid rounded-circle shadow full&quot;]</value>
      <webElementGuid>de87585e-08f6-4d78-9684-37844609c892</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>38331efb-9985-4b8d-b379-6c587b993a51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/user.png</value>
      <webElementGuid>d6b0d5ae-0e03-4123-938f-215c828e99d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-fluid rounded-circle shadow full</value>
      <webElementGuid>ea201b20-1c29-4911-881f-9ba83502a981</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tip</name>
      <type>Main</type>
      <value>admin</value>
      <webElementGuid>013f97ec-d725-484a-9a8b-0b248bbf86a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-for</name>
      <type>Main</type>
      <value>admin</value>
      <webElementGuid>eea086c9-bc65-4d63-b158-bed1cfb9b0c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>currentitem</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>07718e3b-8682-4c7d-998b-e31ca133497a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>admin</value>
      <webElementGuid>8a0d2358-ef27-47d0-a4c3-407f74f0c318</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;wrapper appSection&quot;]/div[@class=&quot;content-wrapper&quot;]/header[@class=&quot;main-header shadow&quot;]/nav[@class=&quot;navbar navbar-static-top&quot;]/ul[@class=&quot;ml-auto d-flex align-items-center list-unstyled mb-0 headerUser&quot;]/li[@class=&quot;nav-item ml-auto user&quot;]/a[@id=&quot;userInfo&quot;]/img[@class=&quot;img-fluid rounded-circle shadow full&quot;]</value>
      <webElementGuid>793ed4cb-218a-431b-b2c7-a06e2d62bd48</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//a[@id='userInfo']/img)[2]</value>
      <webElementGuid>5cae12a1-6de9-443e-a8d9-3cadcdcec8ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/img</value>
      <webElementGuid>820fab5c-bd60-4c36-ab4b-6c1d5808efbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/images/user.png']</value>
      <webElementGuid>01a54fcb-b64f-4ec3-b093-092b25b5d308</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
