<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Assign Annotation_img-fluid rounded-cir_b74cff</name>
   <tag></tag>
   <elementGuidId>09ba6cc9-b95b-4c5b-8ade-ff047b02a572</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[@id='userInfo']/img)[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.img-fluid.rounded-circle.shadow.full</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f37c7d05-317d-473d-9277-73ef37988c2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/user.png</value>
      <webElementGuid>ffad2ea1-8d97-4630-a146-7aa4defa1ac3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-fluid rounded-circle shadow full</value>
      <webElementGuid>4d4da749-cf05-46cb-bce5-1723ac0c62ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tip</name>
      <type>Main</type>
      <value>username1</value>
      <webElementGuid>f1775289-075a-40ab-bff4-919c599212bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-for</name>
      <type>Main</type>
      <value>username1</value>
      <webElementGuid>5708568e-8f57-4da3-9eaf-02d43b61c08e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>currentitem</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>aba06b17-e45d-4d16-807c-5606404d5d50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>username1</value>
      <webElementGuid>46d7ec54-8208-48e9-ada0-cb5d2e235b5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;wrapper appSection&quot;]/div[@class=&quot;content-wrapper&quot;]/header[@class=&quot;main-header shadow&quot;]/nav[@class=&quot;navbar navbar-static-top&quot;]/ul[@class=&quot;ml-auto d-flex align-items-center list-unstyled mb-0 headerUser&quot;]/li[@class=&quot;nav-item ml-auto user&quot;]/a[@id=&quot;userInfo&quot;]/img[@class=&quot;img-fluid rounded-circle shadow full&quot;]</value>
      <webElementGuid>8448f4bd-1ecf-4199-ba05-84b5f506b7a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//a[@id='userInfo']/img)[2]</value>
      <webElementGuid>6ccfff1a-6e76-4116-ab5d-0f63a2c39157</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/img</value>
      <webElementGuid>e29d1179-5911-4fcd-973a-2c37dc7119e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/images/user.png']</value>
      <webElementGuid>017660ec-7dff-4424-9413-e9485792ec89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
