<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Collection Name_dataSourceName</name>
   <tag></tag>
   <elementGuidId>c5f3fc46-bf0b-4f23-baa8-4443605a6128</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;dataSourceName&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='dataSourceName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c3ea9801-2622-48c9-9c04-86cd4cab086f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dataSourceName</value>
      <webElementGuid>d45f15a1-822f-4f72-840b-f15f72215ee4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control   false </value>
      <webElementGuid>c9f5ca91-02ed-4088-9334-8cb9b8641ef0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7c335892-ad29-45e4-b7a0-708b2258b26c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>fullWidth</value>
      <webElementGuid>dac0901d-9f0c-4a1d-81fe-34165bd9322a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;csvForm&quot;)/div[@class=&quot;input padlftrt&quot;]/div[@class=&quot;col-md-12  false&quot;]/input[@class=&quot;form-control   false&quot;]</value>
      <webElementGuid>7e9066ac-efc1-43f2-8a5c-164f469aed3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>93f21725-6537-4631-a0e2-fab500d10d70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dataSourceName</value>
      <webElementGuid>81a1c63b-83b8-4fac-ba7c-8cd6822e077c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control   false </value>
      <webElementGuid>ba8faaf2-a8f6-4a78-a94e-7f24406a2f36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>74b104bb-e971-4b9b-a2c3-85f42117cacf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>fullWidth</value>
      <webElementGuid>abb7ce1c-8ba0-4d6a-871f-64856c86a73c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;csvForm&quot;)/div[@class=&quot;input padlftrt&quot;]/div[@class=&quot;col-md-12  false&quot;]/input[@class=&quot;form-control   false&quot;]</value>
      <webElementGuid>d48c1752-b5b5-43bc-a363-41f3de4e8205</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f4f5406a-abd9-4d08-ae56-6cfcbef3b923</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dataSourceName</value>
      <webElementGuid>be0add07-3863-4b19-b536-923229a1ab72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control   false </value>
      <webElementGuid>60304ec2-dc7d-4486-82fb-93141f04b805</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>90a6aadd-38f1-41e1-8b39-b6a54adbfb58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>fullWidth</value>
      <webElementGuid>f33ad4c5-f665-4db6-b923-8a6b78765164</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;csvForm&quot;)/div[@class=&quot;input padlftrt&quot;]/div[@class=&quot;col-md-12  false&quot;]/input[@class=&quot;form-control   false&quot;]</value>
      <webElementGuid>c5cf3071-99bc-4ad7-8ec6-952526462eab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='dataSourceName']</value>
      <webElementGuid>672be642-4f79-47ee-a1a5-9790c44e3631</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='csvForm']/div/div/input</value>
      <webElementGuid>3a8feb65-bf41-4800-95d2-316d8cad5138</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>1c9a1663-31ca-401f-9ea8-546bd0e8db6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'dataSourceName' and @type = 'text']</value>
      <webElementGuid>8bb5ecca-1de3-4f4d-aa42-ab0af1f3b644</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
