<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Dataset Description_datasetInfo</name>
   <tag></tag>
   <elementGuidId>f6a577d1-8903-4577-9305-6094495ab4ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='datasetInfo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;datasetInfo&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2dbf1063-f474-4a2a-9590-eb8671192ab2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>datasetInfo</value>
      <webElementGuid>667ceb5d-fff5-4ac4-a2fb-7f659aba5f5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control   false </value>
      <webElementGuid>f5a89199-0bde-472f-94c3-802d36aa723a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>26f068fa-34ac-45d6-a164-14d33066cc67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>e086a94c-cc47-48db-b6d1-baf2bae6c134</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>fullWidth</value>
      <webElementGuid>5d6a6bde-f315-4b99-988c-556442d9fd74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;createDatasetForm&quot;)/div[@class=&quot;modal-body&quot;]/div[@class=&quot;list-segment&quot;]/div[@class=&quot;input padlftrt&quot;]/div[@class=&quot;col-md-12  false&quot;]/input[@class=&quot;form-control   false&quot;]</value>
      <webElementGuid>03170b58-f549-4dc9-bf1c-4656ce050233</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>90cd47bf-1745-4905-912e-341cb9cf8157</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>datasetInfo</value>
      <webElementGuid>0c0ed846-3d68-48a5-a6b7-d9dfab3073f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control   false </value>
      <webElementGuid>9dbeddfe-1517-44e0-b02f-1a2a9f03cdb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9f59a491-6c00-4a63-854b-25c25b3dda79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>27a448f5-ce9a-47ea-a163-d95141b2df85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>fullWidth</value>
      <webElementGuid>fe0299e1-e74e-47c3-8b8d-0ce0e545afcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;createDatasetForm&quot;)/div[@class=&quot;modal-body&quot;]/div[@class=&quot;list-segment&quot;]/div[@class=&quot;input padlftrt&quot;]/div[@class=&quot;col-md-12  false&quot;]/input[@class=&quot;form-control   false&quot;]</value>
      <webElementGuid>873f8920-790e-407f-90ce-c946f9dccf3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0f1d39de-a87f-4156-9119-8a78b54737fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>datasetInfo</value>
      <webElementGuid>997fc69d-502e-461b-a4fb-a1981bc29d6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control   false </value>
      <webElementGuid>8f44fa18-932e-4cb5-9ac2-dc6d4e43a02b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>30be62a1-1e3e-465e-9142-b1fe5719bfbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>0c8198a9-819d-4456-9322-6f55f63c1ad2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>fullWidth</value>
      <webElementGuid>9acc4d67-10b4-4ec4-97c8-33c1009db755</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;createDatasetForm&quot;)/div[@class=&quot;modal-body&quot;]/div[@class=&quot;list-segment&quot;]/div[@class=&quot;input padlftrt&quot;]/div[@class=&quot;col-md-12  false&quot;]/input[@class=&quot;form-control   false&quot;]</value>
      <webElementGuid>8f3112dd-31a7-4096-a887-de718612401d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a70e37fc-bcfe-45c3-97ac-8a6e9d70b7c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>datasetInfo</value>
      <webElementGuid>e6acf438-9464-4327-be88-f9f132df6ae8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control   false </value>
      <webElementGuid>3aa4a3cc-8d17-49b5-9714-006f020f43ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2ba94462-6aa2-492f-9799-dbeb6aeef0ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>688624ed-447d-49e1-9d13-6d07ecc5dc03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>fullWidth</value>
      <webElementGuid>8b965403-5768-423b-b881-809f8661ca1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;createDatasetForm&quot;)/div[@class=&quot;modal-body&quot;]/div[@class=&quot;list-segment&quot;]/div[@class=&quot;input padlftrt&quot;]/div[@class=&quot;col-md-12  false&quot;]/input[@class=&quot;form-control   false&quot;]</value>
      <webElementGuid>02c71e2d-44a7-4fd2-a86d-b8bbd7928984</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e6dababa-5766-4cb3-9fe8-6dba003f13c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>datasetInfo</value>
      <webElementGuid>95f44b0e-7f77-454b-8743-b5e91926f7c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control   false </value>
      <webElementGuid>ec33855f-9fb2-4044-af43-e519578f8742</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1272d354-cbc4-4323-aa7a-f4727f0bd97e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>4c53b16f-e785-409d-b2fb-01cfb32d7629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>fullWidth</value>
      <webElementGuid>e747bfa0-92f6-4db9-971b-9dd96434ee35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;createDatasetForm&quot;)/div[@class=&quot;modal-body&quot;]/div[@class=&quot;list-segment&quot;]/div[@class=&quot;input padlftrt&quot;]/div[@class=&quot;col-md-12  false&quot;]/input[@class=&quot;form-control   false&quot;]</value>
      <webElementGuid>029c9c24-4ffd-4bd6-b8a9-6dddbf43d507</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='datasetInfo']</value>
      <webElementGuid>0bf85a28-f189-4f98-9eb3-d835d139435d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='createDatasetForm']/div/div/div[2]/div/input</value>
      <webElementGuid>27e83e3f-a724-4855-b68e-61f385ce58f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>bbada187-6e42-4b28-a7e4-c9810c3a6bbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'datasetInfo' and @type = 'text']</value>
      <webElementGuid>0a0f2ad4-5b48-4bd5-92c2-340985db8f7d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
