<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Findings_findings</name>
   <tag></tag>
   <elementGuidId>9fb95873-4d4d-4250-8d4d-c92586596100</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#findings</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='findings']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8b8ea794-5ee0-4ac9-a158-91046d9ab975</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>53b95799-d976-4b43-a0c7-a46593cd55d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>findings</value>
      <webElementGuid>b6b9a923-e936-4ca8-99e6-202b7abf94c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Finding</value>
      <webElementGuid>05c26e03-f7fd-4d05-8f50-1bc470f1cbfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;findings&quot;)</value>
      <webElementGuid>13d6041c-a1f6-485e-b19d-b7e88054b19d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='findings']</value>
      <webElementGuid>ccfc6355-09b5-47dd-a16a-6d3a61fc7b0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[4]/div/div[5]/div/div/input</value>
      <webElementGuid>3804b750-910e-4001-9616-e873a355ce15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/input</value>
      <webElementGuid>891474fb-5da2-4de3-a6ba-ad95091182c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'findings' and @placeholder = 'Enter Finding']</value>
      <webElementGuid>5885e8eb-9ea0-403a-8000-bc642e593837</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
