<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Mediastinal Widening</name>
   <tag></tag>
   <elementGuidId>3d586da1-7e5a-4566-9dc3-39fc09c4cfa4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='rw_1_listbox']/li[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>983d37ff-5c9a-4d1f-8ac9-a0d82fcf6cbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>3c843145-6ec3-41d2-a71e-8a38a4fa9379</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>5ddcded6-ccf1-43ee-85fb-8e2bcbf73d93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7a9b5a05-a7e4-4ce6-a28e-80fe52887d9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rw-list-option</value>
      <webElementGuid>7584fb64-9795-4dd2-be22-c33740e7134f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mediastinal Widening</value>
      <webElementGuid>fef41b42-8848-4371-8efc-85a024717fec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rw_1_listbox&quot;)/li[@class=&quot;rw-list-option&quot;]</value>
      <webElementGuid>51a599ca-49f5-4926-9638-7183595af194</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='rw_1_listbox']/li[6]</value>
      <webElementGuid>0bbdecf2-1dca-4ff6-a3da-f5ea30b3e044</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lymphadenopathy'])[1]/following::li[1]</value>
      <webElementGuid>5ec6d144-5c10-4ba6-8ea5-2515eb1e2e44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fibrosis'])[1]/following::li[2]</value>
      <webElementGuid>5558eadc-e5b2-4877-b225-83b726b256e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nodule'])[1]/preceding::li[1]</value>
      <webElementGuid>debc8c15-decc-4988-8343-299a6c232322</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pleural Effusion'])[1]/preceding::li[2]</value>
      <webElementGuid>9cb0ff6e-c232-4e5f-86bf-18d4bcdfab33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mediastinal Widening']/parent::*</value>
      <webElementGuid>573c7d4d-41db-4588-87ca-7bdc7260783a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[6]</value>
      <webElementGuid>5c72090c-48f6-436a-a076-2322a75d691c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Mediastinal Widening' or . = 'Mediastinal Widening')]</value>
      <webElementGuid>14cd56fe-e037-4d4d-a079-82c172ae47ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
