<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Collections</name>
   <tag></tag>
   <elementGuidId>74979a28-4d3d-4b2c-8aef-2418e8eb67ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div/div/div/div[2]/div/div/div[2]/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>c8b95430-e7b0-42a6-ad29-ddfd768ae286</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>header_record</value>
      <webElementGuid>92c7b52f-fc1d-460f-9c1c-b33d03f8c20c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Collections</value>
      <webElementGuid>a46aa523-c7f5-4d95-bbcb-aa47ee404a0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;wrapper appSection&quot;]/div[@class=&quot;content-wrapper&quot;]/div[@class=&quot;header bg-gradient-info pb-8 pt-3 pt-md-8&quot;]/div[@class=&quot;mt--7 container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;order-xl-1 mb-5 mb-xl-0 col-xl-5&quot;]/div[@class=&quot;card-profile shadow dashboard_card card&quot;]/div[@class=&quot;pt-0 pt-md-4 card-body&quot;]/div[@class=&quot;text-center&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;record_tiles&quot;]/p[@class=&quot;header_record&quot;]</value>
      <webElementGuid>4c538838-f307-4ce7-9122-96be5e0b5bd9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div/div/div[2]/div/div/div[2]/p</value>
      <webElementGuid>1cfe58fc-cbec-47f2-ba72-f0822ea9edc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Records'])[1]/following::p[4]</value>
      <webElementGuid>443ff332-2a67-4dcd-8a1e-b148cfc77a8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Studies'])[1]/preceding::p[4]</value>
      <webElementGuid>68154c11-0ab6-4534-9f11-ecc4efea31fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome'])[1]/preceding::p[10]</value>
      <webElementGuid>8f0b7119-8969-4159-b2a5-238a4bcba7fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Collections']/parent::*</value>
      <webElementGuid>4fa82c42-c798-454e-aa2c-ca7e9f88ae6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/p</value>
      <webElementGuid>0b36a8c1-9310-430d-a747-8aacf21bd59b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Collections' or . = 'Collections')]</value>
      <webElementGuid>6e2470c6-3b88-4491-82df-2470ade24c0e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
