<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SelectSelecttest1Option2test2test3</name>
   <tag></tag>
   <elementGuidId>43be9951-f42c-4288-b88f-e3e96eecb29a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div[2]/div/div/div/div[3]/div[2]/div/select</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select.form-control</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e8485759-c05f-48ae-9226-5c58aef4ecef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>4970a7ae-2121-4b76-aeb9-02af542b59b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SelectSelecttest1Option2test2test3</value>
      <webElementGuid>db9c5617-d4ee-42ec-a6f9-3344aa5b44c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;wrapper appSection&quot;]/div[@class=&quot;content-wrapper&quot;]/div[1]/div[@class=&quot;App&quot;]/div[2]/div[@class=&quot;row mt-3&quot;]/div[@class=&quot;col-md-8 template_builder&quot;]/div[@class=&quot;mt-3&quot;]/div[3]/div[@class=&quot;bg-template_default&quot;]/div[@class=&quot;list-group-item mb-1 bg-template_items preview_item&quot;]/select[@class=&quot;form-control&quot;]</value>
      <webElementGuid>4de7ad0c-7868-43f9-9758-6f016c99d964</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/div/div/div/div[3]/div[2]/div/select</value>
      <webElementGuid>810ace34-7d16-414c-a2c6-0f561aec0197</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dropdown'])[1]/following::select[1]</value>
      <webElementGuid>afe7da23-87a7-4001-a592-7635c48f2e40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Form Builder'])[1]/following::select[1]</value>
      <webElementGuid>87a02c05-6719-4a4e-a361-c8791c468731</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/preceding::select[1]</value>
      <webElementGuid>e54ff3c7-2781-4cac-bb39-c68f7fc54e8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select']/parent::*</value>
      <webElementGuid>9a0eb5c1-a442-4138-9da0-83248ab33038</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>3fbc70ec-6779-4509-868b-5868955d9a05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[(text() = 'SelectSelecttest1Option2test2test3' or . = 'SelectSelecttest1Option2test2test3')]</value>
      <webElementGuid>8d21ab26-b2b5-4fae-93a4-c7060d152f8b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
