<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Create Template</name>
   <tag></tag>
   <elementGuidId>b44f2e45-0c06-4cf0-ab55-6f92ba47372e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='submitButtonText']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#submitButtonText</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>18fc6a6a-9e66-467f-ac3e-b4f4cef8e1df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>submitButtonText</value>
      <webElementGuid>40061713-921c-4cba-aafd-86bb8a305633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create Template</value>
      <webElementGuid>d7bfddcf-64cb-42b9-b836-52de609a80b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;submitButtonText&quot;)</value>
      <webElementGuid>4dee442f-3577-4050-b414-9fc66f9a0162</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='submitButtonText']</value>
      <webElementGuid>70c1f7a3-16d4-419e-956f-39c7413cb6b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='submitButton']/span</value>
      <webElementGuid>9300138b-3b7a-4b3f-b342-37acf7a8ce0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Template Description'])[1]/following::span[2]</value>
      <webElementGuid>c1cab618-8d62-4aba-8317-22a732510f5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Template Label'])[1]/following::span[3]</value>
      <webElementGuid>696e3d9b-d9f5-4688-90ab-d1f6fa34c191</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'submitButtonText', '&quot;', ')')])[1]/preceding::span[1]</value>
      <webElementGuid>4247a5f6-ebe7-429d-92bd-942e7410bd35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button/span</value>
      <webElementGuid>24484f53-afcd-4cb6-b3c0-a850ec94e10a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'submitButtonText' and (text() = 'Create Template' or . = 'Create Template')]</value>
      <webElementGuid>d8944fc2-759d-42d1-bec3-fb4e6af439cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
