<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Password should have 8-20 characters c_74dd8a</name>
   <tag></tag>
   <elementGuidId>b74e720f-f76b-4fd4-a46e-5ddd2f9d379f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.error</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='registerForm']/div[3]/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>143f5ddf-3379-4b0c-a19e-1cddad94f54a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>error</value>
      <webElementGuid>43c43fc2-0ad8-4079-b267-17e234353701</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Password should have 8-20 characters comprising letters, atleast one uppercase letter, one lower case letter, one number and one special character[!*^$@#%&amp;()]</value>
      <webElementGuid>725c5b30-ee52-47f8-8cd4-6400ba3bab98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registerForm&quot;)/div[@class=&quot;input&quot;]/div[@class=&quot;inptimg name  validation-error&quot;]/span[@class=&quot;error&quot;]</value>
      <webElementGuid>7bc8ef88-0283-4367-a01b-9ac0d5b468cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a946348e-db2f-47eb-967b-c84c083f2cec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>error</value>
      <webElementGuid>93a5350f-ccc3-42ef-bb0f-b174b924efba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Password should have 8-20 characters comprising letters, atleast one uppercase letter, one lower case letter, one number and one special character[!*^$@#%&amp;()]</value>
      <webElementGuid>f19fda7f-6311-4ec5-9e61-bd0167748e1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registerForm&quot;)/div[@class=&quot;input&quot;]/div[@class=&quot;inptimg name  validation-error&quot;]/span[@class=&quot;error&quot;]</value>
      <webElementGuid>9f3db047-960e-4645-b7cd-3e255d34e206</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8003924b-4e32-440f-9e70-43badc2bb2ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>error</value>
      <webElementGuid>49b558ef-a6c3-4f23-a3dd-692dc33205b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Password should have 8-20 characters comprising letters, atleast one uppercase letter, one lower case letter, one number and one special character[!*^$@#%&amp;()]</value>
      <webElementGuid>f56012a7-22ab-47b5-9b96-ee0ce797ee5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registerForm&quot;)/div[@class=&quot;input&quot;]/div[@class=&quot;inptimg name  validation-error&quot;]/span[@class=&quot;error&quot;]</value>
      <webElementGuid>4d71275c-1d00-404e-b257-7c12c2d4467d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registerForm']/div[3]/div/span</value>
      <webElementGuid>3546681d-47d9-45d1-820e-b5c386070e28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Register'])[1]/following::span[4]</value>
      <webElementGuid>3920b8a6-eeb0-42ac-9b52-876b19fef3de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Register'])[2]/preceding::span[2]</value>
      <webElementGuid>faf5fd14-304c-4253-a67d-b11578d3d48c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LOG IN'])[1]/preceding::span[3]</value>
      <webElementGuid>eb9957f8-7d74-421e-9b1f-b811e513eed0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Password should have 8-20 characters comprising letters, atleast one uppercase letter, one lower case letter, one number and one special character[!*^$@#%&amp;()]']/parent::*</value>
      <webElementGuid>17ee941f-5b02-402d-97c8-f5ae4ceaad69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span</value>
      <webElementGuid>5f7cfa2d-9cb5-4a0a-9ec1-9ba6bb9ce57c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Password should have 8-20 characters comprising letters, atleast one uppercase letter, one lower case letter, one number and one special character[!*^$@#%&amp;()]' or . = ' Password should have 8-20 characters comprising letters, atleast one uppercase letter, one lower case letter, one number and one special character[!*^$@#%&amp;()]')]</value>
      <webElementGuid>adbcbe8f-bf2b-4475-a37d-4650e7d4d28b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/span</value>
      <webElementGuid>1812e8de-e94f-40ee-9157-86587eb8226e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Register'])[2]/preceding::span[3]</value>
      <webElementGuid>ac199575-9e0c-4ae7-9090-e1042c0e6cca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
