<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_CT</name>
   <tag></tag>
   <elementGuidId>bb422414-b832-49a2-ada7-10fc78433e40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//span[@id='cnt_ds'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4fd05a6c-7525-4246-b46f-7f2e71205790</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cnt_ds</value>
      <webElementGuid>5ae2b52a-378a-4b48-adfd-5554db0bcf0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CT</value>
      <webElementGuid>aea581ee-2946-4042-b0a3-7850c89f621b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;wrapper appSection&quot;]/div[@class=&quot;content-wrapper&quot;]/div[1]/div[1]/div[@class=&quot;algopage02 circlearea&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;dataset-title-header&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-9&quot;]/h2[@class=&quot;heading2&quot;]/span[2]/span[@id=&quot;cnt_ds&quot;]</value>
      <webElementGuid>1940697b-6441-45b9-ba5a-e3c9f1bbbceb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//span[@id='cnt_ds'])[2]</value>
      <webElementGuid>92a44cbe-0ddc-454a-be39-27fb55b44766</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div/div/div/div/div/h2/span[2]/span</value>
      <webElementGuid>98070bed-5438-4993-9416-0c36a07f1709</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dicom service not running'])[1]/preceding::span[3]</value>
      <webElementGuid>9f8bf1e4-bb8b-4479-8dfa-5c13429b7ec3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/preceding::span[3]</value>
      <webElementGuid>12cd4dea-21cc-4ba7-a285-a667b254ea04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CT']/parent::*</value>
      <webElementGuid>4a9ee949-7395-4813-94b4-f3d267e4f43a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/span</value>
      <webElementGuid>5f490821-40c8-4be2-9872-697265bf3b86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'cnt_ds' and (text() = 'CT' or . = 'CT')]</value>
      <webElementGuid>11094b8e-9b5c-4584-a0c5-be0d27973c2b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
