<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Version v2.2.1_c_logo-mini</name>
   <tag></tag>
   <elementGuidId>9b0a92a6-2a72-4369-80f7-a0214d8cb51b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.logo-mini</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/header/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ea15d389-71a2-4fc0-978a-936e8fc79f0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>logo-mini</value>
      <webElementGuid>8176b48c-0005-4f4b-a757-c2d6f3fd03f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;wrapper appSection&quot;]/div[@class=&quot;content-wrapper&quot;]/header[@class=&quot;main-header shadow&quot;]/a[@class=&quot;logo&quot;]/span[@class=&quot;logo-mini&quot;]</value>
      <webElementGuid>ccf06a89-2a1b-460d-8251-78a0da1e9afb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/header/a/span</value>
      <webElementGuid>e48c5bf9-4a6e-4b99-84f8-6c03d4971a0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/a/span</value>
      <webElementGuid>798ec0da-15f8-4376-a65c-99da9b58b473</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
