<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Enter Password</name>
   <tag></tag>
   <elementGuidId>954aed2f-a65a-4d31-82f2-1895303db0be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='login_form']/div[2]/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.error</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9896c4de-6735-4f7f-9f66-3c0feea22e0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>error</value>
      <webElementGuid>d61aee09-bbcb-40c8-842c-ba072e49b5a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Enter Password</value>
      <webElementGuid>4bcebffa-d8ef-4176-a913-f5ff4dbd961f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login_form&quot;)/div[@class=&quot;input&quot;]/div[@class=&quot;inptimg name  validation-error&quot;]/span[@class=&quot;error&quot;]</value>
      <webElementGuid>48c86fb0-fb91-4c7f-9c08-fc64380c9f5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ff341377-176d-4344-bde2-61a02fb3d856</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>error</value>
      <webElementGuid>dd9de2c5-5bf3-4a04-83d4-3c2ba500e9d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Enter Password</value>
      <webElementGuid>b3519877-50b6-4b94-ba65-5ff2427928dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login_form&quot;)/div[@class=&quot;input&quot;]/div[@class=&quot;inptimg name  validation-error&quot;]/span[@class=&quot;error&quot;]</value>
      <webElementGuid>b106d141-bf50-4493-945b-e1f646050410</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login_form']/div[2]/div/span</value>
      <webElementGuid>5f862a62-c6de-4a11-8f0f-73656a7cb16b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login in to'])[1]/following::span[3]</value>
      <webElementGuid>0585c458-0c13-4424-8fa0-78917bade0f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LOG IN'])[1]/preceding::span[1]</value>
      <webElementGuid>e8a2df5d-f81d-4047-81a6-564e54d5b4cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click here to reset it'])[1]/preceding::span[2]</value>
      <webElementGuid>b9c5f433-3007-4705-9851-b974effa6f25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Enter Password']/parent::*</value>
      <webElementGuid>b0b3d977-28d7-4f18-a43b-2d894f8f0003</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span</value>
      <webElementGuid>4b458072-2572-46e4-9464-cbf480dc29e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Enter Password' or . = ' Enter Password')]</value>
      <webElementGuid>8995c2ad-2a52-4537-ac6a-c931b9667475</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
