<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_12</name>
   <tag></tag>
   <elementGuidId>ce6fcfd8-3f7a-4a90-916a-dd9b2b52f83b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.pt-0.pt-md-0.card-body > ul > li > a > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-tabs-3']/div/div/div/div/div/div[2]/ul/li/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>12012bf0-33d9-4d2c-a2c9-37d978873c75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 12</value>
      <webElementGuid>081fbf57-9ff7-479a-ae84-c751b92697ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-tabs-3&quot;)/div[@class=&quot;panel-content&quot;]/div[@class=&quot;mt--7 container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;order-xl-2 mb-5 mb-xl-0 col-xl-5&quot;]/div[@class=&quot;annotation_card&quot;]/div[@class=&quot;pt-0 pt-md-0 card-body&quot;]/ul[1]/li[1]/a[1]/span[1]</value>
      <webElementGuid>164141ec-bda6-4501-a6ba-9f3c6679a653</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-tabs-3']/div/div/div/div/div/div[2]/ul/li/a/span</value>
      <webElementGuid>a7dfc1bf-ce73-4735-ba3a-48bdccb390be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deployment'])[2]/following::span[1]</value>
      <webElementGuid>a209a815-ba58-4867-88e9-f9e7f9b7ef9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='12']/parent::*</value>
      <webElementGuid>a0bcbed3-f19f-49b3-b211-fadf788e052c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li/a/span</value>
      <webElementGuid>b9f560cf-f691-4f7a-b9a6-2d83f5f0aaa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' 12' or . = ' 12')]</value>
      <webElementGuid>1e1a2243-50c9-417d-a0b4-721d131522f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
