<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Password didnt Match</name>
   <tag></tag>
   <elementGuidId>d3bf58b1-1ab2-4a0b-9226-41b356c39287</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='registerForm']/div[4]/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e4536995-baf6-4fbc-ba02-1a812a190e21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>error</value>
      <webElementGuid>c71a6db0-c119-4150-b78b-c59c2796c1b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Password didn't Match</value>
      <webElementGuid>6480603e-4afc-4078-b6c0-c430b8e8873e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registerForm&quot;)/div[@class=&quot;input&quot;]/div[@class=&quot;inptimg name  validation-error&quot;]/span[@class=&quot;error&quot;]</value>
      <webElementGuid>12bb703f-eef0-44df-9066-4635a4595779</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registerForm']/div[4]/div/span</value>
      <webElementGuid>230b7637-9793-4d81-af2d-bb90402fb6e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Register'])[2]/preceding::span[1]</value>
      <webElementGuid>fdba183b-70e7-4cfc-939b-93a553e656d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LOG IN'])[1]/preceding::span[2]</value>
      <webElementGuid>30e02cf2-49a7-4ca8-895d-881b4965e11e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/span</value>
      <webElementGuid>f38a4e23-f164-4784-b431-d19a4ba690f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = concat(&quot; Password didn&quot; , &quot;'&quot; , &quot;t Match&quot;) or . = concat(&quot; Password didn&quot; , &quot;'&quot; , &quot;t Match&quot;))]</value>
      <webElementGuid>f152cd5c-7d72-4578-ade6-881b495ea1f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
