<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Instances_carpl_checkbox</name>
   <tag></tag>
   <elementGuidId>8e560c95-d570-483c-bcef-9d76d1c58778</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div/div/div/div[2]/div[4]/div/table/thead/tr/th/div/label/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>th.border-t-0.px-6.align-middle.border-l-0.border-r-0.text-xs.whitespace-nowrap.p-4.font-semibold > div > label.main_checkbox > span.carpl_checkbox</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>474b489b-dafd-44db-880d-aa5dc26d131a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>carpl_checkbox</value>
      <webElementGuid>940fc0e8-9714-4d9a-8d9d-308a27b5f450</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;wrapper appSection&quot;]/div[@class=&quot;content-wrapper&quot;]/div[1]/div[1]/div[@class=&quot;algopage02 circlearea&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;datasettble col-md-12&quot;]/div[@class=&quot;table-responsive&quot;]/div[1]/table[@class=&quot;items-center w-full table table-hover border-collapse&quot;]/thead[1]/tr[1]/th[@class=&quot;border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4 font-semibold&quot;]/div[1]/label[@class=&quot;main_checkbox&quot;]/span[@class=&quot;carpl_checkbox&quot;]</value>
      <webElementGuid>96127444-648e-4f51-ba00-0dcbb53e9871</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>91b6344f-5296-485e-9dce-3499218a3d82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>carpl_checkbox</value>
      <webElementGuid>12692ca3-2dd0-44f9-8ceb-3a1ede5931e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;wrapper appSection&quot;]/div[@class=&quot;content-wrapper&quot;]/div[1]/div[1]/div[@class=&quot;algopage02 circlearea&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;datasettble col-md-12&quot;]/div[@class=&quot;table-responsive&quot;]/div[1]/table[@class=&quot;items-center w-full table table-hover border-collapse&quot;]/thead[1]/tr[1]/th[@class=&quot;border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4 font-semibold&quot;]/div[1]/label[@class=&quot;main_checkbox&quot;]/span[@class=&quot;carpl_checkbox&quot;]</value>
      <webElementGuid>af1f95e1-1a66-4075-8612-45eca32d1519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bbe2ff03-5837-49dc-9c22-64ea068f3058</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>carpl_checkbox</value>
      <webElementGuid>7af7122b-1325-4b2b-add1-d5b71fb2bbb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;wrapper appSection&quot;]/div[@class=&quot;content-wrapper&quot;]/div[1]/div[1]/div[@class=&quot;algopage02 circlearea&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;datasettble col-md-12&quot;]/div[@class=&quot;table-responsive&quot;]/div[1]/table[@class=&quot;items-center w-full table table-hover border-collapse&quot;]/thead[1]/tr[1]/th[@class=&quot;border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4 font-semibold&quot;]/div[1]/label[@class=&quot;main_checkbox&quot;]/span[@class=&quot;carpl_checkbox&quot;]</value>
      <webElementGuid>99b63980-918d-4006-a312-3fad47f76c4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>44a496b2-1b31-44f4-969a-27f86b168f82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>carpl_checkbox</value>
      <webElementGuid>8f49e83f-7e0a-474e-b2f6-f5349cf76db5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;wrapper appSection&quot;]/div[@class=&quot;content-wrapper&quot;]/div[1]/div[1]/div[@class=&quot;algopage02 circlearea&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;datasettble col-md-12&quot;]/div[@class=&quot;table-responsive&quot;]/div[1]/table[@class=&quot;items-center w-full table table-hover border-collapse&quot;]/thead[1]/tr[1]/th[@class=&quot;border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4 font-semibold&quot;]/div[1]/label[@class=&quot;main_checkbox&quot;]/span[@class=&quot;carpl_checkbox&quot;]</value>
      <webElementGuid>762dc43e-9020-4fbb-886f-3d5e91e5389b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div/div/div[2]/div[4]/div/table/thead/tr/th/div/label/span</value>
      <webElementGuid>4e3c0b00-8869-44ab-aa18-a13c0ce40a23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th/div/label/span</value>
      <webElementGuid>d6828ab0-5ab8-4bf5-9baf-e14a4e61e9a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
