<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_My Datasets</name>
   <tag></tag>
   <elementGuidId>74694329-551b-4e89-8bd4-8dfa412d1308</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#configurationUl > li > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='configurationUl']/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>53496cc7-dba6-4325-8263-977964d6f948</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/dataset</value>
      <webElementGuid>374e1e17-b942-426c-8726-978836223d31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>My Datasets</value>
      <webElementGuid>d42cf5e4-6445-45e7-921b-7aeb7d9c9b20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;configurationUl&quot;)/li[1]/a[1]</value>
      <webElementGuid>59349948-8fe0-424e-9cce-8cd6be19dbd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8cf73a21-a6c9-431e-888d-f9327ec3da25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/dataset</value>
      <webElementGuid>a788c48c-3589-4430-a0aa-d82527e32493</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>My Datasets</value>
      <webElementGuid>244d1c41-2f6f-4a7d-b417-66830d8c47e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;configurationUl&quot;)/li[1]/a[1]</value>
      <webElementGuid>3b630dbe-4dab-4661-83f1-cd71649714e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='configurationUl']/li/a</value>
      <webElementGuid>2606b4dd-e08d-4a04-83ab-d508ff975633</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'My Datasets')]</value>
      <webElementGuid>a39107bf-4601-4227-aee2-6d997bf446f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dataset Manager'])[1]/following::a[1]</value>
      <webElementGuid>4cac20ab-a52a-4584-8057-fdaec476f31b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WorkFlow'])[1]/following::a[2]</value>
      <webElementGuid>496df684-b07e-4f09-9926-325c1255d1e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Public Datasets'])[1]/preceding::a[1]</value>
      <webElementGuid>0f123e14-5935-4bfd-b0cb-ec28784753d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/preceding::a[2]</value>
      <webElementGuid>9ebed76c-7ac2-44b4-99ef-6692ab563b80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='My Datasets']/parent::*</value>
      <webElementGuid>8cdaa7c1-2f9e-443f-8ae5-31ab76a708d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/dataset')]</value>
      <webElementGuid>79954cab-eed2-4b80-b9c6-15e7664ce305</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/ul/li/a</value>
      <webElementGuid>53c763e0-b2c2-43d7-87f8-79b3bf367fd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/dataset' and (text() = 'My Datasets' or . = 'My Datasets')]</value>
      <webElementGuid>b389ac8d-0103-4b23-9e9d-eed67443c48f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
